Document: chordv
Title: Debian chordv Manual
Author: <insert document author here>
Abstract: This manual describes what chordv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chordv/chordv.sgml.gz

Format: postscript
Files: /usr/share/doc/chordv/chordv.ps.gz

Format: text
Files: /usr/share/doc/chordv/chordv.text.gz

Format: HTML
Index: /usr/share/doc/chordv/html/index.html
Files: /usr/share/doc/chordv/html/*.html
