#############################################################################
# Makefile for building: bin/chordV
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  chordV.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile chordV.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -ILibraries/src/podofo-0.9.5/src -isystem /usr/local/include -Iinclude -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -Ibuild/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = chordVv0.1
DISTDIR = /home/gilles/Developpements/chordV/build/obj/chordVv0.1
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/Libraries/lib/src -L/usr/local/lib -L/usr/lib -lpodofo -lfreetype -lfontconfig -lidn -ljpeg -ltiff -lz -lm -lpng -lcrypto -lssl -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/formconfig.cpp \
		src/lyricsconfig.cpp \
		src/chordconfig.cpp \
		src/textconfig.cpp \
		src/fontchooser.cpp \
		src/fontbutton.cpp \
		src/fontdialog.cpp \
		src/colorbutton.cpp \
		src/lineedittest.cpp \
		src/logmessages.cpp \
		src/editorhighlighter.cpp \
		src/imagebutton.cpp \
		src/examplelabel.cpp \
		src/pagesize.cpp \
		src/processor.cpp \
		src/dialogabout.cpp \
		src/memoryconfig.cpp \
		src/spinboxunit.cpp \
		src/dialogconfiguration.cpp \
		src/settings.cpp \
		src/processortext.cpp \
		src/verticalspacing.cpp \
		src/dialogchorddefinition.cpp \
		src/ChordDetector.cpp \
		src/neck.cpp \
		src/dialogsysteminfo.cpp \
		src/chorddiagram.cpp \
		src/dialogchoosegoodchord.cpp \
		src/dialogsearch.cpp \
		src/dialogreplace.cpp \
		src/processorlyrics.cpp \
		src/language.cpp \
		src/chord.cpp \
		src/langnotes.cpp \
		src/pdfviewer.cpp \
		src/dialogbar.cpp \
		src/processorchord.cpp \
		src/textedit.cpp \
		src/dialogdocumentation.cpp \
		src/formeditor.cpp \
		src/dialogtwolinestochordpro.cpp \
		src/dialogchangechordname.cpp \
		src/forminputoutputchord.cpp \
		src/chordutil.cpp \
		src/normalizelist.cpp build/rcc/qrc_resources.cpp \
		build/moc/moc_mainwindow.cpp \
		build/moc/moc_formconfig.cpp \
		build/moc/moc_lyricsconfig.cpp \
		build/moc/moc_chordconfig.cpp \
		build/moc/moc_textconfig.cpp \
		build/moc/moc_fontchooser.cpp \
		build/moc/moc_fontbutton.cpp \
		build/moc/moc_fontdialog.cpp \
		build/moc/moc_colorbutton.cpp \
		build/moc/moc_imagebutton.cpp \
		build/moc/moc_processor.cpp \
		build/moc/moc_dialogabout.cpp \
		build/moc/moc_memoryconfig.cpp \
		build/moc/moc_spinboxunit.cpp \
		build/moc/moc_dialogconfiguration.cpp \
		build/moc/moc_dialogchorddefinition.cpp \
		build/moc/moc_neck.cpp \
		build/moc/moc_dialogsysteminfo.cpp \
		build/moc/moc_chorddiagram.cpp \
		build/moc/moc_dialogchoosegoodchord.cpp \
		build/moc/moc_dialogsearch.cpp \
		build/moc/moc_dialogreplace.cpp \
		build/moc/moc_dialogbar.cpp \
		build/moc/moc_textedit.cpp \
		build/moc/moc_dialogdocumentation.cpp \
		build/moc/moc_formeditor.cpp \
		build/moc/moc_dialogtwolinestochordpro.cpp \
		build/moc/moc_dialogchangechordname.cpp \
		build/moc/moc_forminputoutputchord.cpp
OBJECTS       = build/obj/main.o \
		build/obj/mainwindow.o \
		build/obj/formconfig.o \
		build/obj/lyricsconfig.o \
		build/obj/chordconfig.o \
		build/obj/textconfig.o \
		build/obj/fontchooser.o \
		build/obj/fontbutton.o \
		build/obj/fontdialog.o \
		build/obj/colorbutton.o \
		build/obj/lineedittest.o \
		build/obj/logmessages.o \
		build/obj/editorhighlighter.o \
		build/obj/imagebutton.o \
		build/obj/examplelabel.o \
		build/obj/pagesize.o \
		build/obj/processor.o \
		build/obj/dialogabout.o \
		build/obj/memoryconfig.o \
		build/obj/spinboxunit.o \
		build/obj/dialogconfiguration.o \
		build/obj/settings.o \
		build/obj/processortext.o \
		build/obj/verticalspacing.o \
		build/obj/dialogchorddefinition.o \
		build/obj/ChordDetector.o \
		build/obj/neck.o \
		build/obj/dialogsysteminfo.o \
		build/obj/chorddiagram.o \
		build/obj/dialogchoosegoodchord.o \
		build/obj/dialogsearch.o \
		build/obj/dialogreplace.o \
		build/obj/processorlyrics.o \
		build/obj/language.o \
		build/obj/chord.o \
		build/obj/langnotes.o \
		build/obj/pdfviewer.o \
		build/obj/dialogbar.o \
		build/obj/processorchord.o \
		build/obj/textedit.o \
		build/obj/dialogdocumentation.o \
		build/obj/formeditor.o \
		build/obj/dialogtwolinestochordpro.o \
		build/obj/dialogchangechordname.o \
		build/obj/forminputoutputchord.o \
		build/obj/chordutil.o \
		build/obj/normalizelist.o \
		build/obj/qrc_resources.o \
		build/obj/moc_mainwindow.o \
		build/obj/moc_formconfig.o \
		build/obj/moc_lyricsconfig.o \
		build/obj/moc_chordconfig.o \
		build/obj/moc_textconfig.o \
		build/obj/moc_fontchooser.o \
		build/obj/moc_fontbutton.o \
		build/obj/moc_fontdialog.o \
		build/obj/moc_colorbutton.o \
		build/obj/moc_imagebutton.o \
		build/obj/moc_processor.o \
		build/obj/moc_dialogabout.o \
		build/obj/moc_memoryconfig.o \
		build/obj/moc_spinboxunit.o \
		build/obj/moc_dialogconfiguration.o \
		build/obj/moc_dialogchorddefinition.o \
		build/obj/moc_neck.o \
		build/obj/moc_dialogsysteminfo.o \
		build/obj/moc_chorddiagram.o \
		build/obj/moc_dialogchoosegoodchord.o \
		build/obj/moc_dialogsearch.o \
		build/obj/moc_dialogreplace.o \
		build/obj/moc_dialogbar.o \
		build/obj/moc_textedit.o \
		build/obj/moc_dialogdocumentation.o \
		build/obj/moc_formeditor.o \
		build/obj/moc_dialogtwolinestochordpro.o \
		build/obj/moc_dialogchangechordname.o \
		build/obj/moc_forminputoutputchord.o
DIST          = Example/deuxdisques.png \
		Example/Chansons.cho3 \
		Example/Chansons.chop \
		Docs/txt/Documentation_en.txt \
		Docs/txt/Documentation_fr.txt \
		Docs/txt/Compilation.md \
		Docs/txt/Todo.md \
		Docs/txt/Makefile \
		Docs/txt/index.txt \
		Test/data/Makefile \
		Test/Docs/txt/Makefile \
		Docs/txt/ChoFormat_en.txt \
		Docs/txt/ChoFormat_fr.txt \
		Docs/txt/fr/Documentation.md \
		Docs/txt/fr/ChoFormat.txt \
		Docs/txt/en/Documentation.txt \
		Docs/txt/en/ChoFormat.txt \
		Docs/img/fr/menupreferences.png \
		Docs/img/fr/preferencegeneral.png \
		Docs/img/fr/fontselection.png \
		Docs/img/fr/preferencetext.png \
		Docs/img/fr/preferencestextcontent.png \
		Docs/img/fr/editor.png \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		chordV.pro include/mainwindow.h \
		include/formconfig.h \
		include/lyricsconfig.h \
		include/chordconfig.h \
		include/textconfig.h \
		include/fontchooser.h \
		include/fontbutton.h \
		include/fontdialog.h \
		include/colorbutton.h \
		include/lineedittest.h \
		include/logmessages.h \
		include/editorhighlighter.h \
		include/imagebutton.h \
		include/examplelabel.h \
		include/pagesize.h \
		include/processor.h \
		include/dialogabout.h \
		include/memoryconfig.h \
		include/spinboxunit.h \
		include/dialogconfiguration.h \
		include/settings.h \
		include/processortext.h \
		include/const.h \
		include/verticalspacing.h \
		include/dialogchorddefinition.h \
		include/ChordDetector.h \
		include/neck.h \
		include/dialogsysteminfo.h \
		include/chorddiagram.h \
		include/dialogchoosegoodchord.h \
		include/dialogsearch.h \
		include/dialogreplace.h \
		include/processorlyrics.h \
		include/language.h \
		include/chord.h \
		include/langnotes.h \
		include/pdfviewer.h \
		include/dialogbar.h \
		include/processorchord.h \
		include/textedit.h \
		include/dialogdocumentation.h \
		include/formeditor.h \
		include/dialogtwolinestochordpro.h \
		include/dialogchangechordname.h \
		include/forminputoutputchord.h \
		include/chordutil.h \
		include/normalizelist.h src/main.cpp \
		src/mainwindow.cpp \
		src/formconfig.cpp \
		src/lyricsconfig.cpp \
		src/chordconfig.cpp \
		src/textconfig.cpp \
		src/fontchooser.cpp \
		src/fontbutton.cpp \
		src/fontdialog.cpp \
		src/colorbutton.cpp \
		src/lineedittest.cpp \
		src/logmessages.cpp \
		src/editorhighlighter.cpp \
		src/imagebutton.cpp \
		src/examplelabel.cpp \
		src/pagesize.cpp \
		src/processor.cpp \
		src/dialogabout.cpp \
		src/memoryconfig.cpp \
		src/spinboxunit.cpp \
		src/dialogconfiguration.cpp \
		src/settings.cpp \
		src/processortext.cpp \
		src/verticalspacing.cpp \
		src/dialogchorddefinition.cpp \
		src/ChordDetector.cpp \
		src/neck.cpp \
		src/dialogsysteminfo.cpp \
		src/chorddiagram.cpp \
		src/dialogchoosegoodchord.cpp \
		src/dialogsearch.cpp \
		src/dialogreplace.cpp \
		src/processorlyrics.cpp \
		src/language.cpp \
		src/chord.cpp \
		src/langnotes.cpp \
		src/pdfviewer.cpp \
		src/dialogbar.cpp \
		src/processorchord.cpp \
		src/textedit.cpp \
		src/dialogdocumentation.cpp \
		src/formeditor.cpp \
		src/dialogtwolinestochordpro.cpp \
		src/dialogchangechordname.cpp \
		src/forminputoutputchord.cpp \
		src/chordutil.cpp \
		src/normalizelist.cpp
QMAKE_TARGET  = chordV
DESTDIR       = bin/
TARGET        = bin/chordV


first: all
####### Build rules

$(TARGET): build/ui/ui_mainwindow.h build/ui/ui_formconfig.h build/ui/ui_fontchooser.h build/ui/ui_dialogabout.h build/ui/ui_dialogconfiguration.h build/ui/ui_dialogchorddefinition.h build/ui/ui_dialogsysteminfo.h build/ui/ui_dialogchoosegoodchord.h build/ui/ui_dialogsearch.h build/ui/ui_dialogreplace.h build/ui/ui_dialogbar.h build/ui/ui_dialogdocumentation.h build/ui/ui_formeditor.h build/ui/ui_dialogtwolinestochordpro.h build/ui/ui_forminputoutputchord.h build/ui/ui_dialogchangechordname.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: chordV.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		chordV.pro \
		Resources/resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile chordV.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
chordV.pro:
Resources/resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile chordV.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents include/mainwindow.h include/formconfig.h include/lyricsconfig.h include/chordconfig.h include/textconfig.h include/fontchooser.h include/fontbutton.h include/fontdialog.h include/colorbutton.h include/lineedittest.h include/logmessages.h include/editorhighlighter.h include/imagebutton.h include/examplelabel.h include/pagesize.h include/processor.h include/dialogabout.h include/memoryconfig.h include/spinboxunit.h include/dialogconfiguration.h include/settings.h include/processortext.h include/const.h include/verticalspacing.h include/dialogchorddefinition.h include/ChordDetector.h include/neck.h include/dialogsysteminfo.h include/chorddiagram.h include/dialogchoosegoodchord.h include/dialogsearch.h include/dialogreplace.h include/processorlyrics.h include/language.h include/chord.h include/langnotes.h include/pdfviewer.h include/dialogbar.h include/processorchord.h include/textedit.h include/dialogdocumentation.h include/formeditor.h include/dialogtwolinestochordpro.h include/dialogchangechordname.h include/forminputoutputchord.h include/chordutil.h include/normalizelist.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/formconfig.cpp src/lyricsconfig.cpp src/chordconfig.cpp src/textconfig.cpp src/fontchooser.cpp src/fontbutton.cpp src/fontdialog.cpp src/colorbutton.cpp src/lineedittest.cpp src/logmessages.cpp src/editorhighlighter.cpp src/imagebutton.cpp src/examplelabel.cpp src/pagesize.cpp src/processor.cpp src/dialogabout.cpp src/memoryconfig.cpp src/spinboxunit.cpp src/dialogconfiguration.cpp src/settings.cpp src/processortext.cpp src/verticalspacing.cpp src/dialogchorddefinition.cpp src/ChordDetector.cpp src/neck.cpp src/dialogsysteminfo.cpp src/chorddiagram.cpp src/dialogchoosegoodchord.cpp src/dialogsearch.cpp src/dialogreplace.cpp src/processorlyrics.cpp src/language.cpp src/chord.cpp src/langnotes.cpp src/pdfviewer.cpp src/dialogbar.cpp src/processorchord.cpp src/textedit.cpp src/dialogdocumentation.cpp src/formeditor.cpp src/dialogtwolinestochordpro.cpp src/dialogchangechordname.cpp src/forminputoutputchord.cpp src/chordutil.cpp src/normalizelist.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui ui/formconfig.ui ui/fontchooser.ui ui/dialogabout.ui ui/dialogconfiguration.ui ui/dialogchorddefinition.ui ui/dialogsysteminfo.ui ui/dialogchoosegoodchord.ui ui/dialogsearch.ui ui/dialogreplace.ui ui/dialogbar.ui ui/dialogdocumentation.ui ui/formeditor.ui ui/dialogtwolinestochordpro.ui ui/forminputoutputchord.ui ui/dialogchangechordname.ui $(DISTDIR)/
	$(COPY_FILE) --parents translations/fr.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/rcc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_resources.cpp
build/rcc/qrc_resources.cpp: Resources/resources.qrc \
		/usr/lib/x86_64-linux-gnu/qt5/bin/rcc \
		Images/icon.png \
		Images/fr.png \
		Images/neck.jpg \
		Images/en.png \
		Images/task-reject.png \
		Images/task-complete.png \
		Images/warning.png \
		Images/cross.png \
		Images/gilles.jpg \
		Images/warning.png \
		translations/fr.ts \
		translations/fr.qm \
		Bd/Chord.db
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resources Resources/resources.qrc -o build/rcc/qrc_resources.cpp

compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp build/moc/moc_formconfig.cpp build/moc/moc_lyricsconfig.cpp build/moc/moc_chordconfig.cpp build/moc/moc_textconfig.cpp build/moc/moc_fontchooser.cpp build/moc/moc_fontbutton.cpp build/moc/moc_fontdialog.cpp build/moc/moc_colorbutton.cpp build/moc/moc_imagebutton.cpp build/moc/moc_processor.cpp build/moc/moc_dialogabout.cpp build/moc/moc_memoryconfig.cpp build/moc/moc_spinboxunit.cpp build/moc/moc_dialogconfiguration.cpp build/moc/moc_dialogchorddefinition.cpp build/moc/moc_neck.cpp build/moc/moc_dialogsysteminfo.cpp build/moc/moc_chorddiagram.cpp build/moc/moc_dialogchoosegoodchord.cpp build/moc/moc_dialogsearch.cpp build/moc/moc_dialogreplace.cpp build/moc/moc_dialogbar.cpp build/moc/moc_textedit.cpp build/moc/moc_dialogdocumentation.cpp build/moc/moc_formeditor.cpp build/moc/moc_dialogtwolinestochordpro.cpp build/moc/moc_dialogchangechordname.cpp build/moc/moc_forminputoutputchord.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp build/moc/moc_formconfig.cpp build/moc/moc_lyricsconfig.cpp build/moc/moc_chordconfig.cpp build/moc/moc_textconfig.cpp build/moc/moc_fontchooser.cpp build/moc/moc_fontbutton.cpp build/moc/moc_fontdialog.cpp build/moc/moc_colorbutton.cpp build/moc/moc_imagebutton.cpp build/moc/moc_processor.cpp build/moc/moc_dialogabout.cpp build/moc/moc_memoryconfig.cpp build/moc/moc_spinboxunit.cpp build/moc/moc_dialogconfiguration.cpp build/moc/moc_dialogchorddefinition.cpp build/moc/moc_neck.cpp build/moc/moc_dialogsysteminfo.cpp build/moc/moc_chorddiagram.cpp build/moc/moc_dialogchoosegoodchord.cpp build/moc/moc_dialogsearch.cpp build/moc/moc_dialogreplace.cpp build/moc/moc_dialogbar.cpp build/moc/moc_textedit.cpp build/moc/moc_dialogdocumentation.cpp build/moc/moc_formeditor.cpp build/moc/moc_dialogtwolinestochordpro.cpp build/moc/moc_dialogchangechordname.cpp build/moc/moc_forminputoutputchord.cpp
build/moc/moc_mainwindow.cpp: include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/mainwindow.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/mainwindow.h -o build/moc/moc_mainwindow.cpp

build/moc/moc_formconfig.cpp: include/formconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/formconfig.h -o build/moc/moc_formconfig.cpp

build/moc/moc_lyricsconfig.cpp: include/formconfig.h \
		include/lyricsconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/lyricsconfig.h -o build/moc/moc_lyricsconfig.cpp

build/moc/moc_chordconfig.cpp: include/formconfig.h \
		include/chordconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/chordconfig.h -o build/moc/moc_chordconfig.cpp

build/moc/moc_textconfig.cpp: include/formconfig.h \
		include/textconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/textconfig.h -o build/moc/moc_textconfig.cpp

build/moc/moc_fontchooser.cpp: include/fontdialog.h \
		include/fontchooser.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/fontchooser.h -o build/moc/moc_fontchooser.cpp

build/moc/moc_fontbutton.cpp: include/fontbutton.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/fontbutton.h -o build/moc/moc_fontbutton.cpp

build/moc/moc_fontdialog.cpp: include/fontdialog.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/fontdialog.h -o build/moc/moc_fontdialog.cpp

build/moc/moc_colorbutton.cpp: include/colorbutton.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/colorbutton.h -o build/moc/moc_colorbutton.cpp

build/moc/moc_imagebutton.cpp: include/imagebutton.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/imagebutton.h -o build/moc/moc_imagebutton.cpp

build/moc/moc_processor.cpp: include/pagesize.h \
		include/formconfig.h \
		include/fontbutton.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/processor.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/processor.h -o build/moc/moc_processor.cpp

build/moc/moc_dialogabout.cpp: include/dialogabout.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogabout.h -o build/moc/moc_dialogabout.cpp

build/moc/moc_memoryconfig.cpp: include/formconfig.h \
		include/memoryconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/memoryconfig.h -o build/moc/moc_memoryconfig.cpp

build/moc/moc_spinboxunit.cpp: include/spinboxunit.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/spinboxunit.h -o build/moc/moc_spinboxunit.cpp

build/moc/moc_dialogconfiguration.cpp: include/dialogconfiguration.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogconfiguration.h -o build/moc/moc_dialogconfiguration.cpp

build/moc/moc_dialogchorddefinition.cpp: include/dialogchorddefinition.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogchorddefinition.h -o build/moc/moc_dialogchorddefinition.cpp

build/moc/moc_neck.cpp: include/neck.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/neck.h -o build/moc/moc_neck.cpp

build/moc/moc_dialogsysteminfo.cpp: include/dialogsysteminfo.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogsysteminfo.h -o build/moc/moc_dialogsysteminfo.cpp

build/moc/moc_chorddiagram.cpp: include/chorddiagram.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/chorddiagram.h -o build/moc/moc_chorddiagram.cpp

build/moc/moc_dialogchoosegoodchord.cpp: include/dialogchoosegoodchord.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogchoosegoodchord.h -o build/moc/moc_dialogchoosegoodchord.cpp

build/moc/moc_dialogsearch.cpp: include/dialogsearch.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogsearch.h -o build/moc/moc_dialogsearch.cpp

build/moc/moc_dialogreplace.cpp: include/dialogreplace.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogreplace.h -o build/moc/moc_dialogreplace.cpp

build/moc/moc_dialogbar.cpp: include/dialogbar.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogbar.h -o build/moc/moc_dialogbar.cpp

build/moc/moc_textedit.cpp: include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/editorhighlighter.h \
		include/textedit.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/textedit.h -o build/moc/moc_textedit.cpp

build/moc/moc_dialogdocumentation.cpp: include/dialogdocumentation.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogdocumentation.h -o build/moc/moc_dialogdocumentation.cpp

build/moc/moc_formeditor.cpp: include/formeditor.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/formeditor.h -o build/moc/moc_formeditor.cpp

build/moc/moc_dialogtwolinestochordpro.cpp: include/dialogtwolinestochordpro.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogtwolinestochordpro.h -o build/moc/moc_dialogtwolinestochordpro.cpp

build/moc/moc_dialogchangechordname.cpp: include/dialogchangechordname.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/dialogchangechordname.h -o build/moc/moc_dialogchangechordname.cpp

build/moc/moc_forminputoutputchord.cpp: include/forminputoutputchord.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/home/gilles/Developpements/chordV/Libraries/src/podofo-0.9.5/src -I/usr/local/include -I/home/gilles/Developpements/chordV/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/forminputoutputchord.h -o build/moc/moc_forminputoutputchord.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_mainwindow.h build/ui/ui_formconfig.h build/ui/ui_fontchooser.h build/ui/ui_dialogabout.h build/ui/ui_dialogconfiguration.h build/ui/ui_dialogchorddefinition.h build/ui/ui_dialogsysteminfo.h build/ui/ui_dialogchoosegoodchord.h build/ui/ui_dialogsearch.h build/ui/ui_dialogreplace.h build/ui/ui_dialogbar.h build/ui/ui_dialogdocumentation.h build/ui/ui_formeditor.h build/ui/ui_dialogtwolinestochordpro.h build/ui/ui_forminputoutputchord.h build/ui/ui_dialogchangechordname.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_mainwindow.h build/ui/ui_formconfig.h build/ui/ui_fontchooser.h build/ui/ui_dialogabout.h build/ui/ui_dialogconfiguration.h build/ui/ui_dialogchorddefinition.h build/ui/ui_dialogsysteminfo.h build/ui/ui_dialogchoosegoodchord.h build/ui/ui_dialogsearch.h build/ui/ui_dialogreplace.h build/ui/ui_dialogbar.h build/ui/ui_dialogdocumentation.h build/ui/ui_formeditor.h build/ui/ui_dialogtwolinestochordpro.h build/ui/ui_forminputoutputchord.h build/ui/ui_dialogchangechordname.h
build/ui/ui_mainwindow.h: ui/mainwindow.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/lyricsconfig.h \
		include/chordconfig.h \
		include/textconfig.h \
		include/memoryconfig.h \
		include/logmessages.h \
		include/formeditor.h \
		include/formconfig.h \
		include/formconfig.h \
		include/formconfig.h \
		include/formconfig.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/mainwindow.ui -o build/ui/ui_mainwindow.h

build/ui/ui_formconfig.h: ui/formconfig.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/spinboxunit.h \
		include/fontbutton.h \
		include/imagebutton.h \
		include/examplelabel.h \
		include/pagesize.h \
		include/verticalspacing.h \
		include/colorbutton.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/formconfig.ui -o build/ui/ui_formconfig.h

build/ui/ui_fontchooser.h: ui/fontchooser.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/colorbutton.h \
		include/fontdialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/fontchooser.ui -o build/ui/ui_fontchooser.h

build/ui/ui_dialogabout.h: ui/dialogabout.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogabout.ui -o build/ui/ui_dialogabout.h

build/ui/ui_dialogconfiguration.h: ui/dialogconfiguration.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/lyricsconfig.h \
		include/chordconfig.h \
		include/textconfig.h \
		include/memoryconfig.h \
		include/formconfig.h \
		include/formconfig.h \
		include/formconfig.h \
		include/formconfig.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogconfiguration.ui -o build/ui/ui_dialogconfiguration.h

build/ui/ui_dialogchorddefinition.h: ui/dialogchorddefinition.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/neck.h \
		include/chorddiagram.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogchorddefinition.ui -o build/ui/ui_dialogchorddefinition.h

build/ui/ui_dialogsysteminfo.h: ui/dialogsysteminfo.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogsysteminfo.ui -o build/ui/ui_dialogsysteminfo.h

build/ui/ui_dialogchoosegoodchord.h: ui/dialogchoosegoodchord.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/chorddiagram.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogchoosegoodchord.ui -o build/ui/ui_dialogchoosegoodchord.h

build/ui/ui_dialogsearch.h: ui/dialogsearch.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogsearch.ui -o build/ui/ui_dialogsearch.h

build/ui/ui_dialogreplace.h: ui/dialogreplace.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogreplace.ui -o build/ui/ui_dialogreplace.h

build/ui/ui_dialogbar.h: ui/dialogbar.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogbar.ui -o build/ui/ui_dialogbar.h

build/ui/ui_dialogdocumentation.h: ui/dialogdocumentation.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogdocumentation.ui -o build/ui/ui_dialogdocumentation.h

build/ui/ui_formeditor.h: ui/formeditor.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/textedit.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/editorhighlighter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/formeditor.ui -o build/ui/ui_formeditor.h

build/ui/ui_dialogtwolinestochordpro.h: ui/dialogtwolinestochordpro.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/forminputoutputchord.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogtwolinestochordpro.ui -o build/ui/ui_dialogtwolinestochordpro.h

build/ui/ui_forminputoutputchord.h: ui/forminputoutputchord.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/forminputoutputchord.ui -o build/ui/ui_forminputoutputchord.h

build/ui/ui_dialogchangechordname.h: ui/dialogchangechordname.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		include/forminputoutputchord.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/dialogchangechordname.ui -o build/ui/ui_dialogchangechordname.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/main.o: src/main.cpp include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/version.h \
		include/language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		build/ui/ui_mainwindow.h \
		include/formeditor.h \
		include/logmessages.h \
		include/lyricsconfig.h \
		include/memoryconfig.h \
		include/textconfig.h \
		include/dialogabout.h \
		include/dialogconfiguration.h \
		include/dialogchorddefinition.h \
		include/dialogsysteminfo.h \
		include/dialogsearch.h \
		include/dialogreplace.h \
		include/dialogbar.h \
		include/dialogdocumentation.h \
		include/dialogtwolinestochordpro.h \
		include/dialogchangechordname.h \
		include/chord.h \
		include/langnotes.h \
		include/chordutil.h \
		include/processortext.h \
		include/processor.h \
		include/pagesize.h \
		include/fontbutton.h \
		include/processorlyrics.h \
		include/processorchord.h \
		include/settings.h \
		include/language.h \
		build/ui/ui_formconfig.h \
		include/verticalspacing.h \
		include/colorbutton.h \
		include/examplelabel.h \
		include/imagebutton.h \
		include/spinboxunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainwindow.o src/mainwindow.cpp

build/obj/formconfig.o: src/formconfig.cpp include/formconfig.h \
		build/ui/ui_formconfig.h \
		include/verticalspacing.h \
		include/colorbutton.h \
		include/examplelabel.h \
		include/fontbutton.h \
		include/imagebutton.h \
		include/pagesize.h \
		include/spinboxunit.h \
		include/settings.h \
		include/language.h \
		include/const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/formconfig.o src/formconfig.cpp

build/obj/lyricsconfig.o: src/lyricsconfig.cpp include/lyricsconfig.h \
		include/formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/lyricsconfig.o src/lyricsconfig.cpp

build/obj/chordconfig.o: src/chordconfig.cpp include/chordconfig.h \
		include/formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chordconfig.o src/chordconfig.cpp

build/obj/textconfig.o: src/textconfig.cpp include/textconfig.h \
		include/formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/textconfig.o src/textconfig.cpp

build/obj/fontchooser.o: src/fontchooser.cpp include/fontchooser.h \
		include/fontdialog.h \
		build/ui/ui_fontchooser.h \
		include/colorbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fontchooser.o src/fontchooser.cpp

build/obj/fontbutton.o: src/fontbutton.cpp include/fontbutton.h \
		include/fontchooser.h \
		include/fontdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fontbutton.o src/fontbutton.cpp

build/obj/fontdialog.o: src/fontdialog.cpp include/fontdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fontdialog.o src/fontdialog.cpp

build/obj/colorbutton.o: src/colorbutton.cpp include/colorbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/colorbutton.o src/colorbutton.cpp

build/obj/lineedittest.o: src/lineedittest.cpp include/lineedittest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/lineedittest.o src/lineedittest.cpp

build/obj/logmessages.o: src/logmessages.cpp include/logmessages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/logmessages.o src/logmessages.cpp

build/obj/editorhighlighter.o: src/editorhighlighter.cpp include/editorhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/editorhighlighter.o src/editorhighlighter.cpp

build/obj/imagebutton.o: src/imagebutton.cpp include/imagebutton.h \
		include/chordutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/imagebutton.o src/imagebutton.cpp

build/obj/examplelabel.o: src/examplelabel.cpp include/examplelabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/examplelabel.o src/examplelabel.cpp

build/obj/pagesize.o: src/pagesize.cpp include/pagesize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/pagesize.o src/pagesize.cpp

build/obj/processor.o: src/processor.cpp include/processor.h \
		include/pagesize.h \
		include/formconfig.h \
		include/fontbutton.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		build/ui/ui_formconfig.h \
		include/verticalspacing.h \
		include/colorbutton.h \
		include/examplelabel.h \
		include/imagebutton.h \
		include/spinboxunit.h \
		build/ui/ui_mainwindow.h \
		include/formeditor.h \
		include/logmessages.h \
		include/lyricsconfig.h \
		include/memoryconfig.h \
		include/textconfig.h \
		include/const.h \
		include/chord.h \
		include/langnotes.h \
		include/chordutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processor.o src/processor.cpp

build/obj/dialogabout.o: src/dialogabout.cpp include/dialogabout.h \
		build/ui/ui_dialogabout.h \
		include/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogabout.o src/dialogabout.cpp

build/obj/memoryconfig.o: src/memoryconfig.cpp include/memoryconfig.h \
		include/formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/memoryconfig.o src/memoryconfig.cpp

build/obj/spinboxunit.o: src/spinboxunit.cpp include/spinboxunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/spinboxunit.o src/spinboxunit.cpp

build/obj/dialogconfiguration.o: src/dialogconfiguration.cpp include/dialogconfiguration.h \
		build/ui/ui_dialogconfiguration.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/lyricsconfig.h \
		include/memoryconfig.h \
		include/textconfig.h \
		include/spinboxunit.h \
		include/settings.h \
		include/language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogconfiguration.o src/dialogconfiguration.cpp

build/obj/settings.o: src/settings.cpp include/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/settings.o src/settings.cpp

build/obj/processortext.o: src/processortext.cpp include/processortext.h \
		include/processor.h \
		include/pagesize.h \
		include/formconfig.h \
		include/fontbutton.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		build/ui/ui_formconfig.h \
		include/verticalspacing.h \
		include/colorbutton.h \
		include/examplelabel.h \
		include/imagebutton.h \
		include/spinboxunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processortext.o src/processortext.cpp

build/obj/verticalspacing.o: src/verticalspacing.cpp include/verticalspacing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/verticalspacing.o src/verticalspacing.cpp

build/obj/dialogchorddefinition.o: src/dialogchorddefinition.cpp include/dialogchorddefinition.h \
		build/ui/ui_dialogchorddefinition.h \
		include/chorddiagram.h \
		include/neck.h \
		include/chordutil.h \
		include/logmessages.h \
		include/dialogchoosegoodchord.h \
		include/language.h \
		include/chord.h \
		include/langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogchorddefinition.o src/dialogchorddefinition.cpp

build/obj/ChordDetector.o: src/ChordDetector.cpp include/ChordDetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ChordDetector.o src/ChordDetector.cpp

build/obj/neck.o: src/neck.cpp include/neck.h \
		include/ChordDetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/neck.o src/neck.cpp

build/obj/dialogsysteminfo.o: src/dialogsysteminfo.cpp include/dialogsysteminfo.h \
		build/ui/ui_dialogsysteminfo.h \
		include/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogsysteminfo.o src/dialogsysteminfo.cpp

build/obj/chorddiagram.o: src/chorddiagram.cpp include/chorddiagram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chorddiagram.o src/chorddiagram.cpp

build/obj/dialogchoosegoodchord.o: src/dialogchoosegoodchord.cpp include/dialogchoosegoodchord.h \
		build/ui/ui_dialogchoosegoodchord.h \
		include/chorddiagram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogchoosegoodchord.o src/dialogchoosegoodchord.cpp

build/obj/dialogsearch.o: src/dialogsearch.cpp include/dialogsearch.h \
		build/ui/ui_dialogsearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogsearch.o src/dialogsearch.cpp

build/obj/dialogreplace.o: src/dialogreplace.cpp include/dialogreplace.h \
		build/ui/ui_dialogreplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogreplace.o src/dialogreplace.cpp

build/obj/processorlyrics.o: src/processorlyrics.cpp include/processorlyrics.h \
		include/processor.h \
		include/pagesize.h \
		include/formconfig.h \
		include/fontbutton.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		build/ui/ui_formconfig.h \
		include/verticalspacing.h \
		include/colorbutton.h \
		include/examplelabel.h \
		include/imagebutton.h \
		include/spinboxunit.h \
		build/ui/ui_mainwindow.h \
		include/formeditor.h \
		include/logmessages.h \
		include/lyricsconfig.h \
		include/memoryconfig.h \
		include/textconfig.h \
		include/chord.h \
		include/langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processorlyrics.o src/processorlyrics.cpp

build/obj/language.o: src/language.cpp include/language.h \
		include/chord.h \
		include/langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/language.o src/language.cpp

build/obj/chord.o: src/chord.cpp include/chord.h \
		include/langnotes.h \
		include/language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chord.o src/chord.cpp

build/obj/langnotes.o: src/langnotes.cpp include/langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/langnotes.o src/langnotes.cpp

build/obj/pdfviewer.o: src/pdfviewer.cpp include/pdfviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/pdfviewer.o src/pdfviewer.cpp

build/obj/dialogbar.o: src/dialogbar.cpp include/dialogbar.h \
		build/ui/ui_dialogbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogbar.o src/dialogbar.cpp

build/obj/processorchord.o: src/processorchord.cpp include/processorchord.h \
		include/processor.h \
		include/pagesize.h \
		include/formconfig.h \
		include/fontbutton.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		build/ui/ui_formconfig.h \
		include/verticalspacing.h \
		include/colorbutton.h \
		include/examplelabel.h \
		include/imagebutton.h \
		include/spinboxunit.h \
		build/ui/ui_mainwindow.h \
		include/formeditor.h \
		include/logmessages.h \
		include/lyricsconfig.h \
		include/memoryconfig.h \
		include/textconfig.h \
		include/chord.h \
		include/langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processorchord.o src/processorchord.cpp

build/obj/textedit.o: src/textedit.cpp include/textedit.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/editorhighlighter.h \
		build/ui/ui_mainwindow.h \
		include/formeditor.h \
		include/logmessages.h \
		include/lyricsconfig.h \
		include/memoryconfig.h \
		include/textconfig.h \
		include/chord.h \
		include/langnotes.h \
		include/dialogchorddefinition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/textedit.o src/textedit.cpp

build/obj/dialogdocumentation.o: src/dialogdocumentation.cpp include/dialogdocumentation.h \
		build/ui/ui_dialogdocumentation.h \
		include/language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogdocumentation.o src/dialogdocumentation.cpp

build/obj/formeditor.o: src/formeditor.cpp include/formeditor.h \
		build/ui/ui_formeditor.h \
		include/textedit.h \
		include/mainwindow.h \
		include/pdfviewer.h \
		include/chordconfig.h \
		include/formconfig.h \
		include/editorhighlighter.h \
		include/dialogbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/formeditor.o src/formeditor.cpp

build/obj/dialogtwolinestochordpro.o: src/dialogtwolinestochordpro.cpp include/dialogtwolinestochordpro.h \
		build/ui/ui_dialogtwolinestochordpro.h \
		include/forminputoutputchord.h \
		include/language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogtwolinestochordpro.o src/dialogtwolinestochordpro.cpp

build/obj/dialogchangechordname.o: src/dialogchangechordname.cpp include/dialogchangechordname.h \
		build/ui/ui_dialogchangechordname.h \
		include/forminputoutputchord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogchangechordname.o src/dialogchangechordname.cpp

build/obj/forminputoutputchord.o: src/forminputoutputchord.cpp include/forminputoutputchord.h \
		build/ui/ui_forminputoutputchord.h \
		include/language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/forminputoutputchord.o src/forminputoutputchord.cpp

build/obj/chordutil.o: src/chordutil.cpp include/chordutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chordutil.o src/chordutil.cpp

build/obj/normalizelist.o: src/normalizelist.cpp include/normalizelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/normalizelist.o src/normalizelist.cpp

build/obj/qrc_resources.o: build/rcc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_resources.o build/rcc/qrc_resources.cpp

build/obj/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainwindow.o build/moc/moc_mainwindow.cpp

build/obj/moc_formconfig.o: build/moc/moc_formconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_formconfig.o build/moc/moc_formconfig.cpp

build/obj/moc_lyricsconfig.o: build/moc/moc_lyricsconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_lyricsconfig.o build/moc/moc_lyricsconfig.cpp

build/obj/moc_chordconfig.o: build/moc/moc_chordconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_chordconfig.o build/moc/moc_chordconfig.cpp

build/obj/moc_textconfig.o: build/moc/moc_textconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_textconfig.o build/moc/moc_textconfig.cpp

build/obj/moc_fontchooser.o: build/moc/moc_fontchooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_fontchooser.o build/moc/moc_fontchooser.cpp

build/obj/moc_fontbutton.o: build/moc/moc_fontbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_fontbutton.o build/moc/moc_fontbutton.cpp

build/obj/moc_fontdialog.o: build/moc/moc_fontdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_fontdialog.o build/moc/moc_fontdialog.cpp

build/obj/moc_colorbutton.o: build/moc/moc_colorbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_colorbutton.o build/moc/moc_colorbutton.cpp

build/obj/moc_imagebutton.o: build/moc/moc_imagebutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_imagebutton.o build/moc/moc_imagebutton.cpp

build/obj/moc_processor.o: build/moc/moc_processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_processor.o build/moc/moc_processor.cpp

build/obj/moc_dialogabout.o: build/moc/moc_dialogabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogabout.o build/moc/moc_dialogabout.cpp

build/obj/moc_memoryconfig.o: build/moc/moc_memoryconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_memoryconfig.o build/moc/moc_memoryconfig.cpp

build/obj/moc_spinboxunit.o: build/moc/moc_spinboxunit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_spinboxunit.o build/moc/moc_spinboxunit.cpp

build/obj/moc_dialogconfiguration.o: build/moc/moc_dialogconfiguration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogconfiguration.o build/moc/moc_dialogconfiguration.cpp

build/obj/moc_dialogchorddefinition.o: build/moc/moc_dialogchorddefinition.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogchorddefinition.o build/moc/moc_dialogchorddefinition.cpp

build/obj/moc_neck.o: build/moc/moc_neck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_neck.o build/moc/moc_neck.cpp

build/obj/moc_dialogsysteminfo.o: build/moc/moc_dialogsysteminfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogsysteminfo.o build/moc/moc_dialogsysteminfo.cpp

build/obj/moc_chorddiagram.o: build/moc/moc_chorddiagram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_chorddiagram.o build/moc/moc_chorddiagram.cpp

build/obj/moc_dialogchoosegoodchord.o: build/moc/moc_dialogchoosegoodchord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogchoosegoodchord.o build/moc/moc_dialogchoosegoodchord.cpp

build/obj/moc_dialogsearch.o: build/moc/moc_dialogsearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogsearch.o build/moc/moc_dialogsearch.cpp

build/obj/moc_dialogreplace.o: build/moc/moc_dialogreplace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogreplace.o build/moc/moc_dialogreplace.cpp

build/obj/moc_dialogbar.o: build/moc/moc_dialogbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogbar.o build/moc/moc_dialogbar.cpp

build/obj/moc_textedit.o: build/moc/moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_textedit.o build/moc/moc_textedit.cpp

build/obj/moc_dialogdocumentation.o: build/moc/moc_dialogdocumentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogdocumentation.o build/moc/moc_dialogdocumentation.cpp

build/obj/moc_formeditor.o: build/moc/moc_formeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_formeditor.o build/moc/moc_formeditor.cpp

build/obj/moc_dialogtwolinestochordpro.o: build/moc/moc_dialogtwolinestochordpro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogtwolinestochordpro.o build/moc/moc_dialogtwolinestochordpro.cpp

build/obj/moc_dialogchangechordname.o: build/moc/moc_dialogchangechordname.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogchangechordname.o build/moc/moc_dialogchangechordname.cpp

build/obj/moc_forminputoutputchord.o: build/moc/moc_forminputoutputchord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_forminputoutputchord.o build/moc/moc_forminputoutputchord.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

