#############################################################################
# Makefile for building: bin/chordV
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  chordV.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile chordV.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -Ibuild/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = chordVv0.1
DISTDIR = /home/gilles/Developpements/chordV/build/obj/chordVv0.1
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/local/lib -L/usr/lib -lpodofo -lfreetype -lfontconfig -lidn -ljpeg -ltiff -lz -lm -lpng -lcrypto -lssl -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		util.cpp \
		formconfig.cpp \
		lyricsconfig.cpp \
		chordconfig.cpp \
		textconfig.cpp \
		fontchooser.cpp \
		fontbutton.cpp \
		fontdialog.cpp \
		colorbutton.cpp \
		lineedittest.cpp \
		logmessages.cpp \
		editorhighlighter.cpp \
		imagebutton.cpp \
		examplelabel.cpp \
		pagesize.cpp \
		processor.cpp \
		dialogabout.cpp \
		memoryconfig.cpp \
		spinboxunit.cpp \
		dialogconfiguration.cpp \
		settings.cpp \
		processortext.cpp \
		verticalspacing.cpp \
		dialogchorddefinition.cpp \
		ChordDetector.cpp \
		neck.cpp \
		dialogsysteminfo.cpp \
		chorddiagram.cpp \
		dialogchoosegoodchord.cpp \
		dialogsearch.cpp \
		dialogreplace.cpp \
		processorlyrics.cpp \
		language.cpp \
		chord.cpp \
		langnotes.cpp \
		pdfviewer.cpp \
		dialogbar.cpp \
		processorchord.cpp \
		textedit.cpp build/rcc/qrc_resources.cpp \
		build/moc/moc_mainwindow.cpp \
		build/moc/moc_formconfig.cpp \
		build/moc/moc_lyricsconfig.cpp \
		build/moc/moc_chordconfig.cpp \
		build/moc/moc_textconfig.cpp \
		build/moc/moc_fontchooser.cpp \
		build/moc/moc_fontbutton.cpp \
		build/moc/moc_fontdialog.cpp \
		build/moc/moc_colorbutton.cpp \
		build/moc/moc_imagebutton.cpp \
		build/moc/moc_processor.cpp \
		build/moc/moc_dialogabout.cpp \
		build/moc/moc_memoryconfig.cpp \
		build/moc/moc_spinboxunit.cpp \
		build/moc/moc_dialogconfiguration.cpp \
		build/moc/moc_dialogchorddefinition.cpp \
		build/moc/moc_neck.cpp \
		build/moc/moc_dialogsysteminfo.cpp \
		build/moc/moc_chorddiagram.cpp \
		build/moc/moc_dialogchoosegoodchord.cpp \
		build/moc/moc_dialogsearch.cpp \
		build/moc/moc_dialogreplace.cpp \
		build/moc/moc_dialogbar.cpp
OBJECTS       = build/obj/main.o \
		build/obj/mainwindow.o \
		build/obj/util.o \
		build/obj/formconfig.o \
		build/obj/lyricsconfig.o \
		build/obj/chordconfig.o \
		build/obj/textconfig.o \
		build/obj/fontchooser.o \
		build/obj/fontbutton.o \
		build/obj/fontdialog.o \
		build/obj/colorbutton.o \
		build/obj/lineedittest.o \
		build/obj/logmessages.o \
		build/obj/editorhighlighter.o \
		build/obj/imagebutton.o \
		build/obj/examplelabel.o \
		build/obj/pagesize.o \
		build/obj/processor.o \
		build/obj/dialogabout.o \
		build/obj/memoryconfig.o \
		build/obj/spinboxunit.o \
		build/obj/dialogconfiguration.o \
		build/obj/settings.o \
		build/obj/processortext.o \
		build/obj/verticalspacing.o \
		build/obj/dialogchorddefinition.o \
		build/obj/ChordDetector.o \
		build/obj/neck.o \
		build/obj/dialogsysteminfo.o \
		build/obj/chorddiagram.o \
		build/obj/dialogchoosegoodchord.o \
		build/obj/dialogsearch.o \
		build/obj/dialogreplace.o \
		build/obj/processorlyrics.o \
		build/obj/language.o \
		build/obj/chord.o \
		build/obj/langnotes.o \
		build/obj/pdfviewer.o \
		build/obj/dialogbar.o \
		build/obj/processorchord.o \
		build/obj/textedit.o \
		build/obj/qrc_resources.o \
		build/obj/moc_mainwindow.o \
		build/obj/moc_formconfig.o \
		build/obj/moc_lyricsconfig.o \
		build/obj/moc_chordconfig.o \
		build/obj/moc_textconfig.o \
		build/obj/moc_fontchooser.o \
		build/obj/moc_fontbutton.o \
		build/obj/moc_fontdialog.o \
		build/obj/moc_colorbutton.o \
		build/obj/moc_imagebutton.o \
		build/obj/moc_processor.o \
		build/obj/moc_dialogabout.o \
		build/obj/moc_memoryconfig.o \
		build/obj/moc_spinboxunit.o \
		build/obj/moc_dialogconfiguration.o \
		build/obj/moc_dialogchorddefinition.o \
		build/obj/moc_neck.o \
		build/obj/moc_dialogsysteminfo.o \
		build/obj/moc_chorddiagram.o \
		build/obj/moc_dialogchoosegoodchord.o \
		build/obj/moc_dialogsearch.o \
		build/obj/moc_dialogreplace.o \
		build/obj/moc_dialogbar.o
DIST          = Example/deuxdisques.png \
		Example/Chansons.cho3 \
		Example/Chansons.chop \
		Docs/txt/Documentation_en.txt \
		Docs/txt/Documentation_fr.txt \
		Docs/txt/Compilation.txt \
		Docs/txt/Todo.txt \
		Docs/txt/Makefile \
		Docs/txt/index.txt \
		Test/data/Makefile \
		Test/Docs/txt/Makefile \
		Docs/txt/ChoFormat_en.txt \
		Docs/txt/ChoFormat_fr.txt \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		chordV.pro mainwindow.h \
		util.h \
		formconfig.h \
		lyricsconfig.h \
		chordconfig.h \
		textconfig.h \
		fontchooser.h \
		fontbutton.h \
		fontdialog.h \
		colorbutton.h \
		lineedittest.h \
		logmessages.h \
		editorhighlighter.h \
		imagebutton.h \
		examplelabel.h \
		pagesize.h \
		processor.h \
		dialogabout.h \
		memoryconfig.h \
		spinboxunit.h \
		dialogconfiguration.h \
		settings.h \
		processortext.h \
		const.h \
		verticalspacing.h \
		dialogchorddefinition.h \
		ChordDetector.h \
		neck.h \
		dialogsysteminfo.h \
		chorddiagram.h \
		dialogchoosegoodchord.h \
		dialogsearch.h \
		dialogreplace.h \
		processorlyrics.h \
		language.h \
		chord.h \
		langnotes.h \
		pdfviewer.h \
		dialogbar.h \
		processorchord.h \
		textedit.h main.cpp \
		mainwindow.cpp \
		util.cpp \
		formconfig.cpp \
		lyricsconfig.cpp \
		chordconfig.cpp \
		textconfig.cpp \
		fontchooser.cpp \
		fontbutton.cpp \
		fontdialog.cpp \
		colorbutton.cpp \
		lineedittest.cpp \
		logmessages.cpp \
		editorhighlighter.cpp \
		imagebutton.cpp \
		examplelabel.cpp \
		pagesize.cpp \
		processor.cpp \
		dialogabout.cpp \
		memoryconfig.cpp \
		spinboxunit.cpp \
		dialogconfiguration.cpp \
		settings.cpp \
		processortext.cpp \
		verticalspacing.cpp \
		dialogchorddefinition.cpp \
		ChordDetector.cpp \
		neck.cpp \
		dialogsysteminfo.cpp \
		chorddiagram.cpp \
		dialogchoosegoodchord.cpp \
		dialogsearch.cpp \
		dialogreplace.cpp \
		processorlyrics.cpp \
		language.cpp \
		chord.cpp \
		langnotes.cpp \
		pdfviewer.cpp \
		dialogbar.cpp \
		processorchord.cpp \
		textedit.cpp
QMAKE_TARGET  = chordV
DESTDIR       = bin/
TARGET        = bin/chordV


first: all
####### Build rules

$(TARGET): build/ui/ui_mainwindow.h build/ui/ui_formconfig.h build/ui/ui_fontchooser.h build/ui/ui_dialogabout.h build/ui/ui_dialogconfiguration.h build/ui/ui_dialogchorddefinition.h build/ui/ui_dialogsysteminfo.h build/ui/ui_dialogchoosegoodchord.h build/ui/ui_dialogsearch.h build/ui/ui_dialogreplace.h build/ui/ui_dialogbar.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: chordV.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		chordV.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile chordV.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Prison.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
chordV.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile chordV.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h util.h formconfig.h lyricsconfig.h chordconfig.h textconfig.h fontchooser.h fontbutton.h fontdialog.h colorbutton.h lineedittest.h logmessages.h editorhighlighter.h imagebutton.h examplelabel.h pagesize.h processor.h dialogabout.h memoryconfig.h spinboxunit.h dialogconfiguration.h settings.h processortext.h const.h verticalspacing.h dialogchorddefinition.h ChordDetector.h neck.h dialogsysteminfo.h chorddiagram.h dialogchoosegoodchord.h dialogsearch.h dialogreplace.h processorlyrics.h language.h chord.h langnotes.h pdfviewer.h dialogbar.h processorchord.h textedit.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp util.cpp formconfig.cpp lyricsconfig.cpp chordconfig.cpp textconfig.cpp fontchooser.cpp fontbutton.cpp fontdialog.cpp colorbutton.cpp lineedittest.cpp logmessages.cpp editorhighlighter.cpp imagebutton.cpp examplelabel.cpp pagesize.cpp processor.cpp dialogabout.cpp memoryconfig.cpp spinboxunit.cpp dialogconfiguration.cpp settings.cpp processortext.cpp verticalspacing.cpp dialogchorddefinition.cpp ChordDetector.cpp neck.cpp dialogsysteminfo.cpp chorddiagram.cpp dialogchoosegoodchord.cpp dialogsearch.cpp dialogreplace.cpp processorlyrics.cpp language.cpp chord.cpp langnotes.cpp pdfviewer.cpp dialogbar.cpp processorchord.cpp textedit.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui formconfig.ui fontchooser.ui dialogabout.ui dialogconfiguration.ui dialogchorddefinition.ui dialogsysteminfo.ui dialogchoosegoodchord.ui dialogsearch.ui dialogreplace.ui dialogbar.ui $(DISTDIR)/
	$(COPY_FILE) --parents fr.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/rcc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_resources.cpp
build/rcc/qrc_resources.cpp: resources.qrc \
		/usr/lib/x86_64-linux-gnu/qt5/bin/rcc \
		Images/icon.png \
		Images/fr.png \
		Images/neck.jpg \
		Images/en.png \
		Images/warning.png \
		Images/gilles.jpg \
		Images/warning.png \
		fr.ts \
		fr.qm \
		Bd/Chord.db
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resources resources.qrc -o build/rcc/qrc_resources.cpp

compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp build/moc/moc_formconfig.cpp build/moc/moc_lyricsconfig.cpp build/moc/moc_chordconfig.cpp build/moc/moc_textconfig.cpp build/moc/moc_fontchooser.cpp build/moc/moc_fontbutton.cpp build/moc/moc_fontdialog.cpp build/moc/moc_colorbutton.cpp build/moc/moc_imagebutton.cpp build/moc/moc_processor.cpp build/moc/moc_dialogabout.cpp build/moc/moc_memoryconfig.cpp build/moc/moc_spinboxunit.cpp build/moc/moc_dialogconfiguration.cpp build/moc/moc_dialogchorddefinition.cpp build/moc/moc_neck.cpp build/moc/moc_dialogsysteminfo.cpp build/moc/moc_chorddiagram.cpp build/moc/moc_dialogchoosegoodchord.cpp build/moc/moc_dialogsearch.cpp build/moc/moc_dialogreplace.cpp build/moc/moc_dialogbar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp build/moc/moc_formconfig.cpp build/moc/moc_lyricsconfig.cpp build/moc/moc_chordconfig.cpp build/moc/moc_textconfig.cpp build/moc/moc_fontchooser.cpp build/moc/moc_fontbutton.cpp build/moc/moc_fontdialog.cpp build/moc/moc_colorbutton.cpp build/moc/moc_imagebutton.cpp build/moc/moc_processor.cpp build/moc/moc_dialogabout.cpp build/moc/moc_memoryconfig.cpp build/moc/moc_spinboxunit.cpp build/moc/moc_dialogconfiguration.cpp build/moc/moc_dialogchorddefinition.cpp build/moc/moc_neck.cpp build/moc/moc_dialogsysteminfo.cpp build/moc/moc_chorddiagram.cpp build/moc/moc_dialogchoosegoodchord.cpp build/moc/moc_dialogsearch.cpp build/moc/moc_dialogreplace.cpp build/moc/moc_dialogbar.cpp
build/moc/moc_mainwindow.cpp: editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		formconfig.h \
		mainwindow.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o build/moc/moc_mainwindow.cpp

build/moc/moc_formconfig.cpp: formconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formconfig.h -o build/moc/moc_formconfig.cpp

build/moc/moc_lyricsconfig.cpp: formconfig.h \
		lyricsconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include lyricsconfig.h -o build/moc/moc_lyricsconfig.cpp

build/moc/moc_chordconfig.cpp: formconfig.h \
		chordconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include chordconfig.h -o build/moc/moc_chordconfig.cpp

build/moc/moc_textconfig.cpp: formconfig.h \
		textconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include textconfig.h -o build/moc/moc_textconfig.cpp

build/moc/moc_fontchooser.cpp: fontdialog.h \
		fontchooser.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include fontchooser.h -o build/moc/moc_fontchooser.cpp

build/moc/moc_fontbutton.cpp: fontbutton.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include fontbutton.h -o build/moc/moc_fontbutton.cpp

build/moc/moc_fontdialog.cpp: fontdialog.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include fontdialog.h -o build/moc/moc_fontdialog.cpp

build/moc/moc_colorbutton.cpp: colorbutton.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include colorbutton.h -o build/moc/moc_colorbutton.cpp

build/moc/moc_imagebutton.cpp: imagebutton.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include imagebutton.h -o build/moc/moc_imagebutton.cpp

build/moc/moc_processor.cpp: pagesize.h \
		formconfig.h \
		fontbutton.h \
		mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		processor.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include processor.h -o build/moc/moc_processor.cpp

build/moc/moc_dialogabout.cpp: dialogabout.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogabout.h -o build/moc/moc_dialogabout.cpp

build/moc/moc_memoryconfig.cpp: formconfig.h \
		memoryconfig.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include memoryconfig.h -o build/moc/moc_memoryconfig.cpp

build/moc/moc_spinboxunit.cpp: spinboxunit.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include spinboxunit.h -o build/moc/moc_spinboxunit.cpp

build/moc/moc_dialogconfiguration.cpp: dialogconfiguration.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogconfiguration.h -o build/moc/moc_dialogconfiguration.cpp

build/moc/moc_dialogchorddefinition.cpp: dialogchorddefinition.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogchorddefinition.h -o build/moc/moc_dialogchorddefinition.cpp

build/moc/moc_neck.cpp: neck.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include neck.h -o build/moc/moc_neck.cpp

build/moc/moc_dialogsysteminfo.cpp: dialogsysteminfo.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogsysteminfo.h -o build/moc/moc_dialogsysteminfo.cpp

build/moc/moc_chorddiagram.cpp: chorddiagram.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include chorddiagram.h -o build/moc/moc_chorddiagram.cpp

build/moc/moc_dialogchoosegoodchord.cpp: dialogchoosegoodchord.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogchoosegoodchord.h -o build/moc/moc_dialogchoosegoodchord.cpp

build/moc/moc_dialogsearch.cpp: dialogsearch.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogsearch.h -o build/moc/moc_dialogsearch.cpp

build/moc/moc_dialogreplace.cpp: dialogreplace.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogreplace.h -o build/moc/moc_dialogreplace.cpp

build/moc/moc_dialogbar.cpp: dialogbar.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/gilles/Developpements/chordV -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialogbar.h -o build/moc/moc_dialogbar.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_mainwindow.h build/ui/ui_formconfig.h build/ui/ui_fontchooser.h build/ui/ui_dialogabout.h build/ui/ui_dialogconfiguration.h build/ui/ui_dialogchorddefinition.h build/ui/ui_dialogsysteminfo.h build/ui/ui_dialogchoosegoodchord.h build/ui/ui_dialogsearch.h build/ui/ui_dialogreplace.h build/ui/ui_dialogbar.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_mainwindow.h build/ui/ui_formconfig.h build/ui/ui_fontchooser.h build/ui/ui_dialogabout.h build/ui/ui_dialogconfiguration.h build/ui/ui_dialogchorddefinition.h build/ui/ui_dialogsysteminfo.h build/ui/ui_dialogchoosegoodchord.h build/ui/ui_dialogsearch.h build/ui/ui_dialogreplace.h build/ui/ui_dialogbar.h
build/ui/ui_mainwindow.h: mainwindow.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		lyricsconfig.h \
		chordconfig.h \
		textconfig.h \
		memoryconfig.h \
		logmessages.h \
		textedit.h \
		formconfig.h \
		formconfig.h \
		formconfig.h \
		formconfig.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o build/ui/ui_mainwindow.h

build/ui/ui_formconfig.h: formconfig.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		spinboxunit.h \
		fontbutton.h \
		imagebutton.h \
		examplelabel.h \
		pagesize.h \
		verticalspacing.h \
		colorbutton.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formconfig.ui -o build/ui/ui_formconfig.h

build/ui/ui_fontchooser.h: fontchooser.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		colorbutton.h \
		fontdialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic fontchooser.ui -o build/ui/ui_fontchooser.h

build/ui/ui_dialogabout.h: dialogabout.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogabout.ui -o build/ui/ui_dialogabout.h

build/ui/ui_dialogconfiguration.h: dialogconfiguration.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		lyricsconfig.h \
		chordconfig.h \
		textconfig.h \
		memoryconfig.h \
		formconfig.h \
		formconfig.h \
		formconfig.h \
		formconfig.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogconfiguration.ui -o build/ui/ui_dialogconfiguration.h

build/ui/ui_dialogchorddefinition.h: dialogchorddefinition.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		neck.h \
		chorddiagram.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogchorddefinition.ui -o build/ui/ui_dialogchorddefinition.h

build/ui/ui_dialogsysteminfo.h: dialogsysteminfo.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogsysteminfo.ui -o build/ui/ui_dialogsysteminfo.h

build/ui/ui_dialogchoosegoodchord.h: dialogchoosegoodchord.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		chorddiagram.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogchoosegoodchord.ui -o build/ui/ui_dialogchoosegoodchord.h

build/ui/ui_dialogsearch.h: dialogsearch.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogsearch.ui -o build/ui/ui_dialogsearch.h

build/ui/ui_dialogreplace.h: dialogreplace.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogreplace.ui -o build/ui/ui_dialogreplace.h

build/ui/ui_dialogbar.h: dialogbar.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialogbar.ui -o build/ui/ui_dialogbar.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/main.o: main.cpp mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		formconfig.h \
		version.h \
		language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o main.cpp

build/obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		formconfig.h \
		build/ui/ui_mainwindow.h \
		logmessages.h \
		lyricsconfig.h \
		memoryconfig.h \
		textconfig.h \
		dialogabout.h \
		dialogconfiguration.h \
		dialogchorddefinition.h \
		dialogsysteminfo.h \
		dialogsearch.h \
		dialogreplace.h \
		dialogbar.h \
		util.h \
		processortext.h \
		processor.h \
		pagesize.h \
		fontbutton.h \
		processorlyrics.h \
		processorchord.h \
		settings.h \
		language.h \
		build/ui/ui_formconfig.h \
		verticalspacing.h \
		colorbutton.h \
		examplelabel.h \
		imagebutton.h \
		spinboxunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainwindow.o mainwindow.cpp

build/obj/util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/util.o util.cpp

build/obj/formconfig.o: formconfig.cpp formconfig.h \
		build/ui/ui_formconfig.h \
		verticalspacing.h \
		colorbutton.h \
		examplelabel.h \
		fontbutton.h \
		imagebutton.h \
		pagesize.h \
		spinboxunit.h \
		settings.h \
		language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/formconfig.o formconfig.cpp

build/obj/lyricsconfig.o: lyricsconfig.cpp lyricsconfig.h \
		formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/lyricsconfig.o lyricsconfig.cpp

build/obj/chordconfig.o: chordconfig.cpp chordconfig.h \
		formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chordconfig.o chordconfig.cpp

build/obj/textconfig.o: textconfig.cpp textconfig.h \
		formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/textconfig.o textconfig.cpp

build/obj/fontchooser.o: fontchooser.cpp fontchooser.h \
		fontdialog.h \
		build/ui/ui_fontchooser.h \
		colorbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fontchooser.o fontchooser.cpp

build/obj/fontbutton.o: fontbutton.cpp fontbutton.h \
		fontchooser.h \
		fontdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fontbutton.o fontbutton.cpp

build/obj/fontdialog.o: fontdialog.cpp fontdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fontdialog.o fontdialog.cpp

build/obj/colorbutton.o: colorbutton.cpp colorbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/colorbutton.o colorbutton.cpp

build/obj/lineedittest.o: lineedittest.cpp lineedittest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/lineedittest.o lineedittest.cpp

build/obj/logmessages.o: logmessages.cpp logmessages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/logmessages.o logmessages.cpp

build/obj/editorhighlighter.o: editorhighlighter.cpp editorhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/editorhighlighter.o editorhighlighter.cpp

build/obj/imagebutton.o: imagebutton.cpp imagebutton.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/imagebutton.o imagebutton.cpp

build/obj/examplelabel.o: examplelabel.cpp examplelabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/examplelabel.o examplelabel.cpp

build/obj/pagesize.o: pagesize.cpp pagesize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/pagesize.o pagesize.cpp

build/obj/processor.o: processor.cpp processor.h \
		pagesize.h \
		formconfig.h \
		fontbutton.h \
		mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		build/ui/ui_formconfig.h \
		verticalspacing.h \
		colorbutton.h \
		examplelabel.h \
		imagebutton.h \
		spinboxunit.h \
		build/ui/ui_mainwindow.h \
		logmessages.h \
		lyricsconfig.h \
		memoryconfig.h \
		textconfig.h \
		const.h \
		chord.h \
		langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processor.o processor.cpp

build/obj/dialogabout.o: dialogabout.cpp dialogabout.h \
		build/ui/ui_dialogabout.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogabout.o dialogabout.cpp

build/obj/memoryconfig.o: memoryconfig.cpp memoryconfig.h \
		formconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/memoryconfig.o memoryconfig.cpp

build/obj/spinboxunit.o: spinboxunit.cpp spinboxunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/spinboxunit.o spinboxunit.cpp

build/obj/dialogconfiguration.o: dialogconfiguration.cpp dialogconfiguration.h \
		build/ui/ui_dialogconfiguration.h \
		chordconfig.h \
		formconfig.h \
		lyricsconfig.h \
		memoryconfig.h \
		textconfig.h \
		spinboxunit.h \
		settings.h \
		language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogconfiguration.o dialogconfiguration.cpp

build/obj/settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/settings.o settings.cpp

build/obj/processortext.o: processortext.cpp processortext.h \
		processor.h \
		pagesize.h \
		formconfig.h \
		fontbutton.h \
		mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		build/ui/ui_formconfig.h \
		verticalspacing.h \
		colorbutton.h \
		examplelabel.h \
		imagebutton.h \
		spinboxunit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processortext.o processortext.cpp

build/obj/verticalspacing.o: verticalspacing.cpp verticalspacing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/verticalspacing.o verticalspacing.cpp

build/obj/dialogchorddefinition.o: dialogchorddefinition.cpp dialogchorddefinition.h \
		build/ui/ui_dialogchorddefinition.h \
		chorddiagram.h \
		neck.h \
		util.h \
		logmessages.h \
		dialogchoosegoodchord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogchorddefinition.o dialogchorddefinition.cpp

build/obj/ChordDetector.o: ChordDetector.cpp ChordDetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ChordDetector.o ChordDetector.cpp

build/obj/neck.o: neck.cpp neck.h \
		ChordDetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/neck.o neck.cpp

build/obj/dialogsysteminfo.o: dialogsysteminfo.cpp dialogsysteminfo.h \
		build/ui/ui_dialogsysteminfo.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogsysteminfo.o dialogsysteminfo.cpp

build/obj/chorddiagram.o: chorddiagram.cpp chorddiagram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chorddiagram.o chorddiagram.cpp

build/obj/dialogchoosegoodchord.o: dialogchoosegoodchord.cpp dialogchoosegoodchord.h \
		build/ui/ui_dialogchoosegoodchord.h \
		chorddiagram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogchoosegoodchord.o dialogchoosegoodchord.cpp

build/obj/dialogsearch.o: dialogsearch.cpp dialogsearch.h \
		build/ui/ui_dialogsearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogsearch.o dialogsearch.cpp

build/obj/dialogreplace.o: dialogreplace.cpp dialogreplace.h \
		build/ui/ui_dialogreplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogreplace.o dialogreplace.cpp

build/obj/processorlyrics.o: processorlyrics.cpp processorlyrics.h \
		processor.h \
		pagesize.h \
		formconfig.h \
		fontbutton.h \
		mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		build/ui/ui_formconfig.h \
		verticalspacing.h \
		colorbutton.h \
		examplelabel.h \
		imagebutton.h \
		spinboxunit.h \
		build/ui/ui_mainwindow.h \
		logmessages.h \
		lyricsconfig.h \
		memoryconfig.h \
		textconfig.h \
		chord.h \
		langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processorlyrics.o processorlyrics.cpp

build/obj/language.o: language.cpp language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/language.o language.cpp

build/obj/chord.o: chord.cpp chord.h \
		langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/chord.o chord.cpp

build/obj/langnotes.o: langnotes.cpp langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/langnotes.o langnotes.cpp

build/obj/pdfviewer.o: pdfviewer.cpp pdfviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/pdfviewer.o pdfviewer.cpp

build/obj/dialogbar.o: dialogbar.cpp dialogbar.h \
		build/ui/ui_dialogbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/dialogbar.o dialogbar.cpp

build/obj/processorchord.o: processorchord.cpp processorchord.h \
		processor.h \
		pagesize.h \
		formconfig.h \
		fontbutton.h \
		mainwindow.h \
		editorhighlighter.h \
		pdfviewer.h \
		chordconfig.h \
		build/ui/ui_formconfig.h \
		verticalspacing.h \
		colorbutton.h \
		examplelabel.h \
		imagebutton.h \
		spinboxunit.h \
		build/ui/ui_mainwindow.h \
		logmessages.h \
		lyricsconfig.h \
		memoryconfig.h \
		textconfig.h \
		chord.h \
		langnotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/processorchord.o processorchord.cpp

build/obj/textedit.o: textedit.cpp textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/textedit.o textedit.cpp

build/obj/qrc_resources.o: build/rcc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_resources.o build/rcc/qrc_resources.cpp

build/obj/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainwindow.o build/moc/moc_mainwindow.cpp

build/obj/moc_formconfig.o: build/moc/moc_formconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_formconfig.o build/moc/moc_formconfig.cpp

build/obj/moc_lyricsconfig.o: build/moc/moc_lyricsconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_lyricsconfig.o build/moc/moc_lyricsconfig.cpp

build/obj/moc_chordconfig.o: build/moc/moc_chordconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_chordconfig.o build/moc/moc_chordconfig.cpp

build/obj/moc_textconfig.o: build/moc/moc_textconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_textconfig.o build/moc/moc_textconfig.cpp

build/obj/moc_fontchooser.o: build/moc/moc_fontchooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_fontchooser.o build/moc/moc_fontchooser.cpp

build/obj/moc_fontbutton.o: build/moc/moc_fontbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_fontbutton.o build/moc/moc_fontbutton.cpp

build/obj/moc_fontdialog.o: build/moc/moc_fontdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_fontdialog.o build/moc/moc_fontdialog.cpp

build/obj/moc_colorbutton.o: build/moc/moc_colorbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_colorbutton.o build/moc/moc_colorbutton.cpp

build/obj/moc_imagebutton.o: build/moc/moc_imagebutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_imagebutton.o build/moc/moc_imagebutton.cpp

build/obj/moc_processor.o: build/moc/moc_processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_processor.o build/moc/moc_processor.cpp

build/obj/moc_dialogabout.o: build/moc/moc_dialogabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogabout.o build/moc/moc_dialogabout.cpp

build/obj/moc_memoryconfig.o: build/moc/moc_memoryconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_memoryconfig.o build/moc/moc_memoryconfig.cpp

build/obj/moc_spinboxunit.o: build/moc/moc_spinboxunit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_spinboxunit.o build/moc/moc_spinboxunit.cpp

build/obj/moc_dialogconfiguration.o: build/moc/moc_dialogconfiguration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogconfiguration.o build/moc/moc_dialogconfiguration.cpp

build/obj/moc_dialogchorddefinition.o: build/moc/moc_dialogchorddefinition.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogchorddefinition.o build/moc/moc_dialogchorddefinition.cpp

build/obj/moc_neck.o: build/moc/moc_neck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_neck.o build/moc/moc_neck.cpp

build/obj/moc_dialogsysteminfo.o: build/moc/moc_dialogsysteminfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogsysteminfo.o build/moc/moc_dialogsysteminfo.cpp

build/obj/moc_chorddiagram.o: build/moc/moc_chorddiagram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_chorddiagram.o build/moc/moc_chorddiagram.cpp

build/obj/moc_dialogchoosegoodchord.o: build/moc/moc_dialogchoosegoodchord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogchoosegoodchord.o build/moc/moc_dialogchoosegoodchord.cpp

build/obj/moc_dialogsearch.o: build/moc/moc_dialogsearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogsearch.o build/moc/moc_dialogsearch.cpp

build/obj/moc_dialogreplace.o: build/moc/moc_dialogreplace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogreplace.o build/moc/moc_dialogreplace.cpp

build/obj/moc_dialogbar.o: build/moc/moc_dialogbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_dialogbar.o build/moc/moc_dialogbar.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

