.TH "include Directory Reference" 3 "Sat Apr 14 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchord\&.h\fP"
.br
.ti -1c
.RI "file \fBchordconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBChordDetector\&.h\fP"
.br
.ti -1c
.RI "file \fBchorddiagram\&.h\fP"
.br
.ti -1c
.RI "file \fBchordutil\&.h\fP"
.br
.ti -1c
.RI "file \fBcolorbutton\&.h\fP"
.br
.ti -1c
.RI "file \fBconst\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogabout\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogbar\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogchangechordname\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogchoosegoodchord\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogchorddefinition\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogconfiguration\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogdocumentation\&.h\fP"
.br
.ti -1c
.RI "file \fBdialognewsong\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogreplace\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogsearch\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogsysteminfo\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogtranspose\&.h\fP"
.br
.ti -1c
.RI "file \fBdialogtwolinestochordpro\&.h\fP"
.br
.ti -1c
.RI "file \fBeditorhighlighter\&.h\fP"
.br
.ti -1c
.RI "file \fBexamplelabel\&.h\fP"
.br
.ti -1c
.RI "file \fBfontbutton\&.h\fP"
.br
.ti -1c
.RI "file \fBfontchooser\&.h\fP"
.br
.ti -1c
.RI "file \fBfontdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBformconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBformeditor\&.h\fP"
.br
.ti -1c
.RI "file \fBforminputoutputchord\&.h\fP"
.br
.ti -1c
.RI "file \fBimagebutton\&.h\fP"
.br
.ti -1c
.RI "file \fBlangnotes\&.h\fP"
.br
.ti -1c
.RI "file \fBlanguage\&.h\fP"
.br
.ti -1c
.RI "file \fBlineedittest\&.h\fP"
.br
.ti -1c
.RI "file \fBlogmessages\&.h\fP"
.br
.ti -1c
.RI "file \fBlyricsconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBmemoryconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBneck\&.h\fP"
.br
.ti -1c
.RI "file \fBnormalizelist\&.h\fP"
.br
.ti -1c
.RI "file \fBpagesize\&.h\fP"
.br
.ti -1c
.RI "file \fBpdfviewer\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessor\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessorchord\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessorlyrics\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessortext\&.h\fP"
.br
.ti -1c
.RI "file \fBsettings\&.h\fP"
.br
.ti -1c
.RI "file \fBspinboxunit\&.h\fP"
.br
.ti -1c
.RI "file \fBtextconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBtextedit\&.h\fP"
.br
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.ti -1c
.RI "file \fBverticalspacing\&.h\fP"
.br
.in -1c
