.TH "src/ChordDetector.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ChordDetector.h
.SH SYNOPSIS
.br
.PP
\fC#include <QStringList>\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChordDetector\fP"
.br
.RI "The \fBChordDetector\fP class allow to detect a chord from listNotes\&. It is used on guitar neck to transform a list of notes to QStringList of chords given by the method \fBdetectChord()\fP; The list of notes given to constructor are for example A, E, F The algorythm is given buy the tblscitype of the ChordV database\&. The ChordV Database containes two tables : tblscitype and Chords\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
