.TH "ChordUtil" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChordUtil \- Some utilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chordutil\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QStringList \fBLastProjects\fP ()"
.br
.RI "LastProjects give the list of lastProjects used to add in \fBMainWindow\fP the list of last project opened\&. The list is stored in QSettings\&. "
.ti -1c
.RI "static void \fBMemorizeProject\fP (QString filename)"
.br
.RI "MemorizeProject when we add a new project save the last 10 projects ( if 10 is the number of project stored)\&. If the project is contained in the list, all the project are stored, if the given project is new, the older will be removed\&. "
.ti -1c
.RI "static QString \fBgetLastDirectory\fP ()"
.br
.RI "getLastDirectory retrieve the name of the last directory opened\&. It is useful to memorize the last directory open by user in QFileFialog or other\&. "
.ti -1c
.RI "static void \fBsetLastDirectory\fP (QString filename)"
.br
.RI "setLastDirectory set the last directory opened\&. See \fBgetLastDirectory()\fP "
.ti -1c
.RI "static QString \fBtoRomain\fP (int i)"
.br
.RI "toRomain convert 1 to I, 5 to V, 9 to IX "
.ti -1c
.RI "static QStringList \fBNormalize\fP (QStringList FretAnd6Strings)"
.br
.RI "Normalize old fonction for compatubility ( Obsolete) "
.ti -1c
.RI "static int \fBfromRomain\fP (QString i)"
.br
.RI "fromRomain convert from I to 1, from V to 5, from IX to 9 "
.in -1c
.SH "Detailed Description"
.PP 
Some utilities\&. 

The \fBChordUtil\fP class a set of static function given information 
.SH "Member Function Documentation"
.PP 
.SS "int ChordUtil::fromRomain (QString i)\fC [static]\fP"

.PP
fromRomain convert from I to 1, from V to 5, from IX to 9 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP : QString of value in romain notation 
.RE
.PP
\fBReturns:\fP
.RS 4
the value in integer 
.RE
.PP

.SS "QString ChordUtil::getLastDirectory ()\fC [static]\fP"

.PP
getLastDirectory retrieve the name of the last directory opened\&. It is useful to memorize the last directory open by user in QFileFialog or other\&. 
.PP
\fBReturns:\fP
.RS 4
: the name of the last directory opened 
.RE
.PP

.SS "QStringList ChordUtil::LastProjects ()\fC [static]\fP"

.PP
LastProjects give the list of lastProjects used to add in \fBMainWindow\fP the list of last project opened\&. The list is stored in QSettings\&. 
.PP
\fBReturns:\fP
.RS 4
the QStringList with all the lastproject 
.RE
.PP

.SS "void ChordUtil::MemorizeProject (QString filename)\fC [static]\fP"

.PP
MemorizeProject when we add a new project save the last 10 projects ( if 10 is the number of project stored)\&. If the project is contained in the list, all the project are stored, if the given project is new, the older will be removed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP the name of the new project 
.RE
.PP

.SS "QStringList ChordUtil::Normalize (QStringList FretAnd6Strings)\fC [static]\fP"

.PP
Normalize old fonction for compatubility ( Obsolete) 
.PP
\fBParameters:\fP
.RS 4
\fIFretAnd6Strings\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void ChordUtil::setLastDirectory (QString filename)\fC [static]\fP"

.PP
setLastDirectory set the last directory opened\&. See \fBgetLastDirectory()\fP 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP : the directory whe want to memorize 
.RE
.PP

.SS "QString ChordUtil::toRomain (int i)\fC [static]\fP"

.PP
toRomain convert 1 to I, 5 to V, 9 to IX 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP : the integer value 
.RE
.PP
\fBReturns:\fP
.RS 4
a string with romain notation 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
