.TH "ColorButton" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorButton \- The \fBColorButton\fP class allows to draw the color of QToolButton when user choose a color after click on button\&. The allow to show the color chooser by the button\&. This class is QtDesigner/QtCreator complient\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colorbutton\&.h>\fP
.PP
Inherits QToolButton\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBColorChanged\fP (QColor color)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorButton\fP (QWidget *parent=0)"
.br
.RI "\fBColorButton\fP construtor with the parent widget argument allowing to use in QtDesigner\&. "
.ti -1c
.RI "QColor \fBgetColor\fP ()"
.br
.RI "getColor get the color of the button "
.ti -1c
.RI "void \fBsetColor\fP (QColor color)"
.br
.RI "setColor set the color of the button "
.in -1c
.SH "Detailed Description"
.PP 
The \fBColorButton\fP class allows to draw the color of QToolButton when user choose a color after click on button\&. The allow to show the color chooser by the button\&. This class is QtDesigner/QtCreator complient\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColorButton::ColorButton (QWidget * parent = \fC0\fP)"

.PP
\fBColorButton\fP construtor with the parent widget argument allowing to use in QtDesigner\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP : the parent 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ColorButton::ColorChanged (QColor color)\fC [signal]\fP"

.SS "QColor ColorButton::getColor ()\fC [inline]\fP"

.PP
getColor get the color of the button 
.PP
\fBReturns:\fP
.RS 4
the color in QColor type 
.RE
.PP

.SS "void ColorButton::setColor (QColor color)"

.PP
setColor set the color of the button 
.PP
\fBParameters:\fP
.RS 4
\fIcolor\fP giver with QColor attribute 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
