.TH "src/colorbutton.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/colorbutton.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'colorbutton\&.h'\fP
.br
\fC#include <QColorDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
