.TH "src/colorbutton.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/colorbutton.h
.SH SYNOPSIS
.br
.PP
\fC#include <QToolButton>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColorButton\fP"
.br
.RI "The \fBColorButton\fP class allows to draw the color of QToolButton when user choose a color after click on button\&. The allow to show the color chooser by the button\&. This class is QtDesigner/QtCreator complient\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
