.TH "Const" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Const \- The \fBConst\fP class set of constant classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <const\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPageNumber\fP { \fBNo\fP, \fBCenter\fP, \fBOutside\fP }
.RI "The PageNumber enum can be No for no pagnumber, Center ou Outside\&. ""
.br
.ti -1c
.RI "enum \fBPlex\fP { \fBSimplex\fP, \fBDuplex\fP }
.RI "The Plex enum can be Simplex it one side is printed, or Duplex if each page is printed\&. ""
.br
.ti -1c
.RI "enum \fBPageStyle\fP { \fBNumber\fP, \fBNumberAndTiret\fP, \fBNumberDivideByPageNUmber\fP, \fBNumberAndArrows\fP }
.RI "The PageStyle enum type of page number on button of each page Number is 1 Number and Tiret - 1 - NumberDivideByPageNUmber 1/50 NumberAndArrows <1> ""
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPageNumber\fP \fBgetPageNumber\fP (int i)"
.br
.RI "getPageNumber return No Center or Outsde from 0 1 or 2 parameter "
.in -1c
.SH "Detailed Description"
.PP 
The \fBConst\fP class set of constant classes\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBConst::PageNumber\fP"

.PP
The PageNumber enum can be No for no pagnumber, Center ou Outside\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINo \fP\fP
.TP
\fB\fICenter \fP\fP
.TP
\fB\fIOutside \fP\fP
.SS "enum \fBConst::PageStyle\fP"

.PP
The PageStyle enum type of page number on button of each page Number is 1 Number and Tiret - 1 - NumberDivideByPageNUmber 1/50 NumberAndArrows <1> 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINumber \fP\fP
.TP
\fB\fINumberAndTiret \fP\fP
.TP
\fB\fINumberDivideByPageNUmber \fP\fP
.TP
\fB\fINumberAndArrows \fP\fP
.SS "enum \fBConst::Plex\fP"

.PP
The Plex enum can be Simplex it one side is printed, or Duplex if each page is printed\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISimplex \fP\fP
.TP
\fB\fIDuplex \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "static \fBPageNumber\fP Const::getPageNumber (int i)\fC [inline]\fP, \fC [static]\fP"

.PP
getPageNumber return No Center or Outsde from 0 1 or 2 parameter 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
