.TH "DialogChangeChordName" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogChangeChordName \- The \fBDialogChangeChordName\fP class used to change language of name of a chord by transposition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogchangechordname\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogChangeChordName\fP (QWidget *parent=0)"
.br
.RI "\fBDialogChangeChordName\fP Dialog to Change chord Name : language or transposition\&. "
.ti -1c
.RI "\fB~DialogChangeChordName\fP ()"
.br
.ti -1c
.RI "QString \fBgetFromLang\fP ()"
.br
.RI "getFromLang after change return from language "
.ti -1c
.RI "QString \fBgetToLang\fP ()"
.br
.RI "getToLang after change return to language "
.ti -1c
.RI "QString \fBgetFromMin\fP ()"
.br
.RI "getFromMin after change return Minor notation for from conversion\&. Exampele m or - "
.ti -1c
.RI "QString \fBgetToMin\fP ()"
.br
.RI "getToMin after change return Minor notation for to conversion\&. Exampele m or - "
.ti -1c
.RI "int \fBgetFromLangIndex\fP ()"
.br
.RI "getFromLangIndex return index of FromLang combobox "
.ti -1c
.RI "int \fBgetToLangIndex\fP ()"
.br
.RI "getToLangIndex return index of ToLang Combobox "
.ti -1c
.RI "int \fBgetToMinIndex\fP ()"
.br
.RI "getToMinIndex return index of ToLang Combobox "
.ti -1c
.RI "int \fBgetFromMinIndex\fP ()"
.br
.RI "getFromMinIndex return index of FromLang Combobox "
.ti -1c
.RI "void \fBsetFromLang\fP (int lang)"
.br
.RI "setFromLang set the index of FromLang combobox "
.ti -1c
.RI "void \fBsetToLang\fP (int min)"
.br
.RI "setToLang set tje index of ToFrom combobox "
.ti -1c
.RI "void \fBsetFromMin\fP (int lang)"
.br
.RI "setFromMin idem with Minor letter "
.ti -1c
.RI "void \fBsetToMin\fP (int min)"
.br
.RI "setToMin same as above with To record "
.ti -1c
.RI "bool \fBOkDialog\fP ()"
.br
.RI "OkDialog the dialog return ok (true) or cancel(false) "
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogChangeChordName\fP class used to change language of name of a chord by transposition\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogChangeChordName::DialogChangeChordName (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogChangeChordName\fP Dialog to Change chord Name : language or transposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogChangeChordName::~DialogChangeChordName ()"

.SH "Member Function Documentation"
.PP 
.SS "QString DialogChangeChordName::getFromLang ()"

.PP
getFromLang after change return from language 
.PP
\fBReturns:\fP
.RS 4
QString for language for example Français or English 
.RE
.PP

.SS "int DialogChangeChordName::getFromLangIndex ()"

.PP
getFromLangIndex return index of FromLang combobox 
.PP
\fBReturns:\fP
.RS 4
int with the value of index of FromLang 
.RE
.PP

.SS "QString DialogChangeChordName::getFromMin ()"

.PP
getFromMin after change return Minor notation for from conversion\&. Exampele m or - 
.PP
\fBReturns:\fP
.RS 4
QString with letter for minor 
.RE
.PP

.SS "int DialogChangeChordName::getFromMinIndex ()"

.PP
getFromMinIndex return index of FromLang Combobox 
.PP
\fBReturns:\fP
.RS 4
integer with the value of index of FromLang 
.RE
.PP

.SS "QString DialogChangeChordName::getToLang ()"

.PP
getToLang after change return to language 
.PP
\fBReturns:\fP
.RS 4
QString for language for example Français or English 
.RE
.PP

.SS "int DialogChangeChordName::getToLangIndex ()"

.PP
getToLangIndex return index of ToLang Combobox 
.PP
\fBReturns:\fP
.RS 4
integer with the value of index of FromLang 
.RE
.PP

.SS "QString DialogChangeChordName::getToMin ()"

.PP
getToMin after change return Minor notation for to conversion\&. Exampele m or - 
.PP
\fBReturns:\fP
.RS 4
QString with letter for minor 
.RE
.PP

.SS "int DialogChangeChordName::getToMinIndex ()"

.PP
getToMinIndex return index of ToLang Combobox 
.PP
\fBReturns:\fP
.RS 4
integer with the value of index of ToLang 
.RE
.PP

.SS "bool DialogChangeChordName::OkDialog ()"

.PP
OkDialog the dialog return ok (true) or cancel(false) 
.PP
\fBReturns:\fP
.RS 4
the bool is true only if ok button is clicked 
.RE
.PP

.SS "void DialogChangeChordName::setFromLang (int lang)"

.PP
setFromLang set the index of FromLang combobox 
.PP
\fBParameters:\fP
.RS 4
\fIlang\fP the index of FromLang 
.RE
.PP

.SS "void DialogChangeChordName::setFromMin (int lang)"

.PP
setFromMin idem with Minor letter 
.PP
\fBParameters:\fP
.RS 4
\fIlang\fP 
.RE
.PP

.SS "void DialogChangeChordName::setToLang (int min)"

.PP
setToLang set tje index of ToFrom combobox 
.PP
\fBParameters:\fP
.RS 4
\fImin\fP the to langa 
.RE
.PP

.SS "void DialogChangeChordName::setToMin (int min)"

.PP
setToMin same as above with To record 
.PP
\fBParameters:\fP
.RS 4
\fImin\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
