.TH "DialogChooseGoodChord" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogChooseGoodChord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogchoosegoodchord\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBError\fP (QString texterror)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogChooseGoodChord\fP (QString oldname, QString oldvalue, QString newname, QString newvalue, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~DialogChooseGoodChord\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogChooseGoodChord::DialogChooseGoodChord (QString oldname, QString oldvalue, QString newname, QString newvalue, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "DialogChooseGoodChord::~DialogChooseGoodChord ()"

.SH "Member Function Documentation"
.PP 
.SS "void DialogChooseGoodChord::Error (QString texterror)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
