.TH "DialogAbout" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogAbout \- The \fBDialogAbout\fP class show the Dialog about\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogabout\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogAbout\fP (QWidget *parent=0)"
.br
.RI "\fBDialogAbout\fP the constructor to show the About Dialog\&. "
.ti -1c
.RI "\fB~DialogAbout\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogAbout\fP class show the Dialog about\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogAbout::DialogAbout (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogAbout\fP the constructor to show the About Dialog\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogAbout::~DialogAbout ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
