.TH "DialogSystemInfo" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogSystemInfo \- The \fBDialogSystemInfo\fP class this dialog show a set of system informations like date of compilation, release version, Git SHA1 version, program arguments, configuration file, Database location, PID of process, location of language information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogsysteminfo\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogSystemInfo\fP (QWidget *parent=0)"
.br
.RI "\fBDialogSystemInfo\fP the constructor open the dialog window with parent giver in argument\&. "
.ti -1c
.RI "\fB~DialogSystemInfo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogSystemInfo\fP class this dialog show a set of system informations like date of compilation, release version, Git SHA1 version, program arguments, configuration file, Database location, PID of process, location of language information\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogSystemInfo::DialogSystemInfo (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogSystemInfo\fP the constructor open the dialog window with parent giver in argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogSystemInfo::~DialogSystemInfo ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
