.TH "src/dialogchorddefinition.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dialogchorddefinition.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QModelIndex>\fP
.br
\fC#include <QSqlTableModel>\fP
.br
\fC#include <QTableView>\fP
.br
\fC#include <QSqlQueryModel>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QPaintEvent>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogChordDefinition\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
