.TH "src/dialogtranspose.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dialogtranspose.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogTranspose\fP"
.br
.RI "The \fBDialogTranspose\fP class is a Dialog class to ask how many chroma negative or positive the user wants to transpose\&. It ask if the chord has to be with parenthesis or no and ask if just the current chord has to print translated, all the chord in the current line, all the chord on the current song or all the chord of the current booklet\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
