.TH "src/dialogconfiguration.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dialogconfiguration.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dialogconfiguration\&.h'\fP
.br
\fC#include 'ui_dialogconfiguration\&.h'\fP
.br
\fC#include 'spinboxunit\&.h'\fP
.br
\fC#include 'settings\&.h'\fP
.br
\fC#include 'language\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFileInfoList>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
