.TH "DialogTwoLinesToChordPro" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogTwoLinesToChordPro \- The \fBDialogTwoLinesToChordPro\fP class is an utility to convert song in two lines :  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogtwolinestochordpro\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogTwoLinesToChordPro\fP (QWidget *parent=0)"
.br
.RI "\fBDialogTwoLinesToChordPro\fP the dialog windows\&. "
.ti -1c
.RI "\fB~DialogTwoLinesToChordPro\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogTwoLinesToChordPro\fP class is an utility to convert song in two lines : 

C D Hello how are you
.PP
to chord in one line : [C] Hello how are [D]you 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogTwoLinesToChordPro::DialogTwoLinesToChordPro (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogTwoLinesToChordPro\fP the dialog windows\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogTwoLinesToChordPro::~DialogTwoLinesToChordPro ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
