.TH "DialogDocumentation" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogDocumentation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogdocumentation\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogDocumentation\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~DialogDocumentation\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogDocumentation::DialogDocumentation (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "DialogDocumentation::~DialogDocumentation ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
