.TH "DialogChordDefinition" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogChordDefinition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogchorddefinition\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBError\fP (QString message)"
.br
.ti -1c
.RI "void \fBChordToInsert\fP (QString chord)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogChordDefinition\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~DialogChordDefinition\fP ()"
.br
.ti -1c
.RI "void \fBSetChordLanguage\fP (QString lang, QString minor)"
.br
.ti -1c
.RI "void \fBActiveInsertButton\fP ()"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBShowChords\fP (QStringList chordnames, QString chortdstring)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogChordDefinition::DialogChordDefinition (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "DialogChordDefinition::~DialogChordDefinition ()"

.SH "Member Function Documentation"
.PP 
.SS "void DialogChordDefinition::ActiveInsertButton ()"

.SS "void DialogChordDefinition::ChordToInsert (QString chord)\fC [signal]\fP"

.SS "void DialogChordDefinition::Error (QString message)\fC [signal]\fP"

.SS "void DialogChordDefinition::SetChordLanguage (QString lang, QString minor)"

.SS "void DialogChordDefinition::ShowChords (QStringList chordnames, QString chortdstring)\fC [protected]\fP, \fC [slot]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
