.TH "DialogBar" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogBar \- The \fBDialogBar\fP class allow to choose the bar dialog for example 4/4 or 3/4 information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogbar\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogBar\fP (QWidget *parent=0)"
.br
.RI "\fBDialogBar\fP is complient with QtDesigner allowing to promote a widget to \fBDialogBar\fP\&. "
.ti -1c
.RI "\fB~DialogBar\fP ()"
.br
.ti -1c
.RI "bool \fBcanceled\fP ()"
.br
.RI "canceled the dialog was canceled "
.ti -1c
.RI "QString \fBvalue\fP ()"
.br
.RI "return value like 4/4 or 3/4 "
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogBar\fP class allow to choose the bar dialog for example 4/4 or 3/4 information\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogBar::DialogBar (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogBar\fP is complient with QtDesigner allowing to promote a widget to \fBDialogBar\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogBar::~DialogBar ()"

.SH "Member Function Documentation"
.PP 
.SS "bool DialogBar::canceled ()"

.PP
canceled the dialog was canceled 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "QString DialogBar::value ()"

.PP
return value like 4/4 or 3/4 
.PP
\fBReturns:\fP
.RS 4
the QString value returned 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
