.TH "src/dialogchoosegoodchord.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dialogchoosegoodchord.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dialogchoosegoodchord\&.h'\fP
.br
\fC#include 'ui_dialogchoosegoodchord\&.h'\fP
.br
\fC#include <QSqlQuery>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
