.TH "DialogConfiguration" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogconfiguration\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBLanguageChanged\fP (QString lang)"
.br
.ti -1c
.RI "void \fBPdfReaderChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogConfiguration\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetTranslator\fP (QTranslator *translator)"
.br
.ti -1c
.RI "\fB~DialogConfiguration\fP ()"
.br
.ti -1c
.RI "void \fBInitSettings\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetLanguageComboBox\fP (QComboBox *ptr)"
.br
.ti -1c
.RI "static QString \fBgetTranslationQmFileName\fP (QString lang)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogConfiguration::DialogConfiguration (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "DialogConfiguration::~DialogConfiguration ()"

.SH "Member Function Documentation"
.PP 
.SS "static QString DialogConfiguration::getTranslationQmFileName (QString lang)\fC [static]\fP"

.SS "void DialogConfiguration::InitSettings ()"

.SS "void DialogConfiguration::LanguageChanged (QString lang)\fC [signal]\fP"

.SS "void DialogConfiguration::PdfReaderChanged ()\fC [signal]\fP"

.SS "static void DialogConfiguration::setLanguageComboBox (QComboBox * ptr)\fC [static]\fP"

.SS "void DialogConfiguration::setTranslator (QTranslator * translator)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
