.TH "DialogTranspose" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogTranspose \- The \fBDialogTranspose\fP class is a Dialog class to ask how many chroma negative or positive the user wants to transpose\&. It ask if the chord has to be with parenthesis or no and ask if just the current chord has to print translated, all the chord in the current line, all the chord on the current song or all the chord of the current booklet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogtranspose\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBAskChange\fP (int halftonenumber, bool parenthesis, int Range)"
.br
.RI "AskChange ask change with halftonenumber, parenthesis yes or no, and range defined as just the current chord has to print translated, all the chord in the current line, all the chord on the current song or all the chord of the current booklet\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogTranspose\fP (QWidget *parent=0)"
.br
.RI "\fBDialogTranspose\fP the QDialog constructor\&. "
.ti -1c
.RI "\fB~DialogTranspose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogTranspose\fP class is a Dialog class to ask how many chroma negative or positive the user wants to transpose\&. It ask if the chord has to be with parenthesis or no and ask if just the current chord has to print translated, all the chord in the current line, all the chord on the current song or all the chord of the current booklet\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogTranspose::DialogTranspose (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogTranspose\fP the QDialog constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogTranspose::~DialogTranspose ()"

.SH "Member Function Documentation"
.PP 
.SS "void DialogTranspose::AskChange (int halftonenumber, bool parenthesis, int Range)\fC [signal]\fP"

.PP
AskChange ask change with halftonenumber, parenthesis yes or no, and range defined as just the current chord has to print translated, all the chord in the current line, all the chord on the current song or all the chord of the current booklet\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhalftonenumber\fP 
.br
\fIparenthesis\fP 
.br
\fIRange\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
