.TH "DialogReplace" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogReplace \- The \fBDialogReplace\fP class allo to search and replace words in Editor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogreplace\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBSearchBack\fP (QString text, bool casesensitive, bool wordonly)"
.br
.ti -1c
.RI "void \fBSearch\fP (QString text, bool casesensitive, bool wordonly)"
.br
.ti -1c
.RI "void \fBReplace\fP (QString textfrom, QString textto, bool All, bool casesentisite, bool wordonly, bool back)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogReplace\fP (QWidget *parent=0)"
.br
.RI "\fBDialogReplace\fP show a replace dialog to allow to search and replace inside Editor\&. "
.ti -1c
.RI "\fB~DialogReplace\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDialogReplace\fP class allo to search and replace words in Editor\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogReplace::DialogReplace (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBDialogReplace\fP show a replace dialog to allow to search and replace inside Editor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "DialogReplace::~DialogReplace ()"

.SH "Member Function Documentation"
.PP 
.SS "void DialogReplace::Replace (QString textfrom, QString textto, bool All, bool casesentisite, bool wordonly, bool back)\fC [signal]\fP"

.SS "void DialogReplace::Search (QString text, bool casesensitive, bool wordonly)\fC [signal]\fP"

.SS "void DialogReplace::SearchBack (QString text, bool casesensitive, bool wordonly)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
