.TH "EditorHighlighter" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditorHighlighter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editorhighlighter\&.h>\fP
.PP
Inherits QSyntaxHighlighter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditorHighlighter\fP (QTextDocument *parent)"
.br
.ti -1c
.RI "void \fBhighlightBlock\fP (const QString &text)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditorHighlighter::EditorHighlighter (QTextDocument * parent)"

.SH "Member Function Documentation"
.PP 
.SS "void EditorHighlighter::highlightBlock (const QString & text)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
