.TH "src/editorhighlighter.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/editorhighlighter.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSyntaxHighlighter>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEditorHighlighter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
