.TH "ExampleLabel" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <examplelabel\&.h>\fP
.PP
Inherits QLabel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExampleLabel\fP (QWidget *parent=0, Qt::WindowFlags f=0)"
.br
.ti -1c
.RI "void \fBsetColor\fP (QFont font, QColor color, QColor background)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExampleLabel::ExampleLabel (QWidget * parent = \fC0\fP, Qt::WindowFlags f = \fC0\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void ExampleLabel::setColor (QFont font, QColor color, QColor background)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
