.TH "src/fontdialog.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fontdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QFontDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFontDialog\fP"
.br
.RI "The \fBFontDialog\fP class is a derived class from QFontDialog to force QFontDialog to be a QWidget that can be included as a promoted Widget\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
