.TH "FontDialog" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FontDialog \- The \fBFontDialog\fP class is a derived class from QFontDialog to force QFontDialog to be a QWidget that can be included as a promoted Widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fontdialog\&.h>\fP
.PP
Inherits QFontDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontDialog\fP (QWidget *parent=0)"
.br
.RI "\fBFontDialog\fP can be a promoted widget displaying font\&. "
.ti -1c
.RI "\fB~FontDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBFontDialog\fP class is a derived class from QFontDialog to force QFontDialog to be a QWidget that can be included as a promoted Widget\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FontDialog::FontDialog (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBFontDialog\fP can be a promoted widget displaying font\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SS "FontDialog::~FontDialog ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
