.TH "FontButton" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FontButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fontbutton\&.h>\fP
.PP
Inherits QToolButton\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBSelectedFont\fP (QFont font, QColor text, QColor background)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsendSelectedFont\fP (QFont font, QColor text, QColor background)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontButton\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetFamily\fP (QString family)"
.br
.ti -1c
.RI "void \fBsetColor\fP (QColor color)"
.br
.ti -1c
.RI "void \fBsetBackgroundColor\fP (QColor color)"
.br
.ti -1c
.RI "void \fBsetWeight\fP (int i)"
.br
.ti -1c
.RI "void \fBsetItalic\fP (bool b)"
.br
.ti -1c
.RI "void \fBsetPointsize\fP (int size)"
.br
.ti -1c
.RI "void \fBsetFont\fP (QFont font)"
.br
.ti -1c
.RI "QFont \fBgetFont\fP ()"
.br
.ti -1c
.RI "QColor \fBgetBackgroundColor\fP ()"
.br
.ti -1c
.RI "QColor \fBgetTextColor\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FontButton::FontButton (QWidget * parent)"

.SH "Member Function Documentation"
.PP 
.SS "QColor FontButton::getBackgroundColor ()\fC [inline]\fP"

.SS "QFont FontButton::getFont ()\fC [inline]\fP"

.SS "QColor FontButton::getTextColor ()\fC [inline]\fP"

.SS "void FontButton::SelectedFont (QFont font, QColor text, QColor background)\fC [slot]\fP"

.SS "void FontButton::sendSelectedFont (QFont font, QColor text, QColor background)\fC [signal]\fP"

.SS "void FontButton::setBackgroundColor (QColor color)"

.SS "void FontButton::setColor (QColor color)"

.SS "void FontButton::setFamily (QString family)"

.SS "void FontButton::setFont (QFont font)"

.SS "void FontButton::setItalic (bool b)"

.SS "void FontButton::setPointsize (int size)"

.SS "void FontButton::setWeight (int i)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
