.TH "FontChooser" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FontChooser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fontchooser\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBSelectFont\fP (QFont font, QColor text, QColor background)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontChooser\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetFont\fP (QFont font, QColor text, QColor background)"
.br
.ti -1c
.RI "\fB~FontChooser\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FontChooser::FontChooser (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "FontChooser::~FontChooser ()"

.SH "Member Function Documentation"
.PP 
.SS "void FontChooser::SelectFont (QFont font, QColor text, QColor background)\fC [signal]\fP"

.SS "void FontChooser::setFont (QFont font, QColor text, QColor background)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
