.TH "FormInputOutputChord" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormInputOutputChord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <forminputoutputchord\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormInputOutputChord\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "QString \fBgetInputLang\fP ()"
.br
.ti -1c
.RI "QString \fBgetOutputLang\fP ()"
.br
.ti -1c
.RI "QString \fBgetInputMinor\fP ()"
.br
.ti -1c
.RI "QString \fBgetOutputMinor\fP ()"
.br
.ti -1c
.RI "int \fBgetInputLangIndex\fP ()"
.br
.ti -1c
.RI "int \fBgetOutputLangIndex\fP ()"
.br
.ti -1c
.RI "int \fBgetInputMinorIndex\fP ()"
.br
.ti -1c
.RI "int \fBgetOutputMinorIndex\fP ()"
.br
.ti -1c
.RI "void \fBsetOutputMinor\fP (int index)"
.br
.ti -1c
.RI "void \fBsetInputMinor\fP (int index)"
.br
.ti -1c
.RI "void \fBsetInputLang\fP (int index)"
.br
.ti -1c
.RI "void \fBsetOutputLang\fP (int lang)"
.br
.ti -1c
.RI "\fB~FormInputOutputChord\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FormInputOutputChord::FormInputOutputChord (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "FormInputOutputChord::~FormInputOutputChord ()"

.SH "Member Function Documentation"
.PP 
.SS "QString FormInputOutputChord::getInputLang ()"

.SS "int FormInputOutputChord::getInputLangIndex ()"

.SS "QString FormInputOutputChord::getInputMinor ()"

.SS "int FormInputOutputChord::getInputMinorIndex ()"

.SS "QString FormInputOutputChord::getOutputLang ()"

.SS "int FormInputOutputChord::getOutputLangIndex ()"

.SS "QString FormInputOutputChord::getOutputMinor ()"

.SS "int FormInputOutputChord::getOutputMinorIndex ()"

.SS "void FormInputOutputChord::setInputLang (int index)"

.SS "void FormInputOutputChord::setInputMinor (int index)"

.SS "void FormInputOutputChord::setOutputLang (int lang)"

.SS "void FormInputOutputChord::setOutputMinor (int index)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
