.TH "src/formeditor.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/formeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'formeditor\&.h'\fP
.br
\fC#include 'ui_formeditor\&.h'\fP
.br
\fC#include 'dialogbar\&.h'\fP
.br
\fC#include 'language\&.h'\fP
.br
\fC#include 'chord\&.h'\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QHeaderView>\fP
.br
\fC#include <QTextCursor>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
