.TH "src/formconfig.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/formconfig.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QRegExp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFormConfig\fP"
.br
.RI "The \fBFormConfig\fP class manage the display of configuration of attributes : (Color, Fonts, \&.\&.\&.) for the definition of each booklet\&. It is used in Preference and also on each project\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
