.TH "src/formconfig.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/formconfig.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'formconfig\&.h'\fP
.br
\fC#include 'ui_formconfig\&.h'\fP
.br
\fC#include 'colorbutton\&.h'\fP
.br
\fC#include 'examplelabel\&.h'\fP
.br
\fC#include 'settings\&.h'\fP
.br
\fC#include 'language\&.h'\fP
.br
\fC#include 'const\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QSettings>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
