.TH "ImageButton" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imagebutton\&.h>\fP
.PP
Inherits QToolButton\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBImageSelelected\fP (QString Image)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageButton\fP (QWidget *parent)"
.br
.ti -1c
.RI "QString \fBgetImage\fP ()"
.br
.ti -1c
.RI "void \fBsetImage\fP (QString image)"
.br
.ti -1c
.RI "void \fBsetProjectPath\fP (QString path)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImageButton::ImageButton (QWidget * parent)"

.SH "Member Function Documentation"
.PP 
.SS "QString ImageButton::getImage ()"

.SS "void ImageButton::ImageSelelected (QString Image)\fC [signal]\fP"

.SS "void ImageButton::setImage (QString image)"

.SS "void ImageButton::setProjectPath (QString path)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
