.TH "src/imagebutton.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/imagebutton.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'imagebutton\&.h'\fP
.br
\fC#include 'chordutil\&.h'\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QDebug>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
