.TH "LangNotes" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LangNotes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <langnotes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLangNotes\fP ()"
.br
.ti -1c
.RI "QString \fBnoteLocale\fP (QString englishnote)"
.br
.ti -1c
.RI "QString \fBnoteEnglish\fP (QString localenote)"
.br
.ti -1c
.RI "QString \fBnote\fP (QString lang, QString note)"
.br
.ti -1c
.RI "QStringList \fBEnglishNotes\fP ()"
.br
.ti -1c
.RI "QStringList \fBLocalNotes\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LangNotes::LangNotes ()"

.SH "Member Function Documentation"
.PP 
.SS "QStringList LangNotes::EnglishNotes ()"

.SS "QStringList LangNotes::LocalNotes ()"

.SS "QString LangNotes::note (QString lang, QString note)"

.SS "QString LangNotes::noteEnglish (QString localenote)"

.SS "QString LangNotes::noteLocale (QString englishnote)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
