.TH "src/langnotes.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/langnotes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'langnotes\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
