.TH "LineEditTest" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineEditTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lineedittest\&.h>\fP
.PP
Inherits QLineEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLineEditTest\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetTestSentence\fP (QString text)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LineEditTest::LineEditTest (QWidget * parent)"

.SH "Member Function Documentation"
.PP 
.SS "void LineEditTest::setTestSentence (QString text)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
