.TH "MainWindow" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- The \fBMainWindow\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBChangeLanguage\fP (QString)"
.br
.RI "ChangeLanguage retranslate all the child window and tha main window\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.ti -1c
.RI "void \fBsetTranstator\fP (QTranslator *tr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBMainWindow\fP class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "MainWindow::~MainWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "void MainWindow::ChangeLanguage (QString)\fC [slot]\fP"

.PP
ChangeLanguage retranslate all the child window and tha main window\&. 
.SS "void MainWindow::setTranstator (QTranslator * tr)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
