.TH "src/mainwindow.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pdfviewer\&.h'\fP
.br
\fC#include 'chordconfig\&.h'\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <QToolButton>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QLabel>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "The \fBMainWindow\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
