.TH "src/mainwindow.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'dialogabout\&.h'\fP
.br
\fC#include 'dialogconfiguration\&.h'\fP
.br
\fC#include 'dialogchorddefinition\&.h'\fP
.br
\fC#include 'dialogsysteminfo\&.h'\fP
.br
\fC#include 'dialogsearch\&.h'\fP
.br
\fC#include 'dialogreplace\&.h'\fP
.br
\fC#include 'dialogbar\&.h'\fP
.br
\fC#include 'dialogdocumentation\&.h'\fP
.br
\fC#include 'dialogtwolinestochordpro\&.h'\fP
.br
\fC#include 'dialogchangechordname\&.h'\fP
.br
\fC#include 'dialogtranspose\&.h'\fP
.br
\fC#include 'lyricsconfig\&.h'\fP
.br
\fC#include 'formconfig\&.h'\fP
.br
\fC#include 'textconfig\&.h'\fP
.br
\fC#include 'memoryconfig\&.h'\fP
.br
\fC#include 'chord\&.h'\fP
.br
\fC#include 'chordutil\&.h'\fP
.br
\fC#include 'processortext\&.h'\fP
.br
\fC#include 'processorlyrics\&.h'\fP
.br
\fC#include 'processorchord\&.h'\fP
.br
\fC#include 'settings\&.h'\fP
.br
\fC#include 'logmessages\&.h'\fP
.br
\fC#include 'language\&.h'\fP
.br
\fC#include 'pdfviewer\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QShortcut>\fP
.br
\fC#include 'ui_formconfig\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
