.TH "src/neck.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/neck.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'neck\&.h'\fP
.br
\fC#include 'ChordDetector\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QMouseEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
