.TH "src/neck.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/neck.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsView>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNeck\fP"
.br
.RI "The \fBNeck\fP class is derivated of graphicsView to allow to show a guitar neck and analyse the string touched to calculate chord\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
