.TH "NormalizeList" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NormalizeList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <normalizelist\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNormalizeList\fP (QList< QVariant > list)"
.br
.ti -1c
.RI "QList< QVariant > \fBgetNormalizedList\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NormalizeList::NormalizeList (QList< QVariant > list)"

.SH "Member Function Documentation"
.PP 
.SS "QList< QVariant > NormalizeList::getNormalizedList ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
