.TH "PageSize" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageSize \- The \fBPageSize\fP class is a QCombobox derived type containing list of format like A4 A4 B2 \&.\&.\&. the method get the size\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pagesize\&.h>\fP
.PP
Inherits QComboBox\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPageSize\fP (QWidget *parent)"
.br
.RI "\fBPageSize\fP is a QtDesigner complient Widget\&. "
.ti -1c
.RI "QString \fBgetUnit\fP ()"
.br
.RI "getUnit return unit of QComboBox "
.ti -1c
.RI "double \fBgetWidth\fP ()"
.br
.RI "getWidth return the Width in mm unit "
.ti -1c
.RI "double \fBgetHeight\fP ()"
.br
.RI "getHeight return the Height in mm unit "
.ti -1c
.RI "void \fBsetCurrentText\fP (const QString &text)"
.br
.RI "setCurrentText : set custom text "
.ti -1c
.RI "QString \fBfindSize\fP (double w, double h, bool &landscape)"
.br
.RI "findSize from width and height return format and landscape or portrait orientation "
.ti -1c
.RI "void \fBsetCurrentTextByValue\fP (QString value)"
.br
.RI "setCurrentTextByValue set the current text positionned by value "
.in -1c
.SH "Detailed Description"
.PP 
The \fBPageSize\fP class is a QCombobox derived type containing list of format like A4 A4 B2 \&.\&.\&. the method get the size\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PageSize::PageSize (QWidget * parent)"

.PP
\fBPageSize\fP is a QtDesigner complient Widget\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "QString PageSize::findSize (double w, double h, bool & landscape)"

.PP
findSize from width and height return format and landscape or portrait orientation 
.PP
\fBParameters:\fP
.RS 4
\fIw\fP :double for width paper size 
.br
\fIh\fP : double for height paper size 
.br
\fIlandscape\fP : return true if landscape 
.RE
.PP
\fBReturns:\fP
.RS 4
the QString format (for example A4) 
.RE
.PP

.SS "double PageSize::getHeight ()"

.PP
getHeight return the Height in mm unit 
.PP
\fBReturns:\fP
.RS 4
double height 
.RE
.PP

.SS "QString PageSize::getUnit ()"

.PP
getUnit return unit of QComboBox 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "double PageSize::getWidth ()"

.PP
getWidth return the Width in mm unit 
.PP
\fBReturns:\fP
.RS 4
double width 
.RE
.PP

.SS "void PageSize::setCurrentText (const QString & text)"

.PP
setCurrentText : set custom text 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP in QString 
.RE
.PP

.SS "void PageSize::setCurrentTextByValue (QString value)"

.PP
setCurrentTextByValue set the current text positionned by value 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
