.TH "src/pagesize.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pagesize.h
.SH SYNOPSIS
.br
.PP
\fC#include <QComboBox>\fP
.br
\fC#include <QMultiMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPageSize\fP"
.br
.RI "The \fBPageSize\fP class is a QCombobox derived type containing list of format like A4 A4 B2 \&.\&.\&. the method get the size\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
