.TH "PdfViewer" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PdfViewer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pdfviewer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPdfViewer\fP (QString filename, QWidget *parent)"
.br
.ti -1c
.RI "bool \fBgetStatus\fP ()"
.br
.ti -1c
.RI "QString \fBgetStatusError\fP ()"
.br
.ti -1c
.RI "QString \fBgetStatusInfo\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PdfViewer::PdfViewer (QString filename, QWidget * parent)"

.SH "Member Function Documentation"
.PP 
.SS "bool PdfViewer::getStatus ()"

.SS "QString PdfViewer::getStatusError ()"

.SS "QString PdfViewer::getStatusInfo ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
