.TH "src/pdfviewer.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pdfviewer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pdfviewer\&.h'\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QFileInfo>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
