.TH "ProcessorChord" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcessorChord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <processorchord\&.h>\fP
.PP
Inherits \fBProcessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessorChord\fP (Ui::MainWindow *ui1, Ui::FormConfig *ui2)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProcessorChord::ProcessorChord (Ui::MainWindow * ui1, Ui::FormConfig * ui2)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
