.TH "src/processorchord.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/processorchord.h
.SH SYNOPSIS
.br
.PP
\fC#include 'processor\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <podofo/podofo\&.h>\fP
.br
\fC#include <podofo/podofo\-base\&.h>\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProcessorChord\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
