.TH "src/processor.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/processor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pagesize\&.h'\fP
.br
\fC#include 'formconfig\&.h'\fP
.br
\fC#include 'fontbutton\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QDate>\fP
.br
\fC#include <QMap>\fP
.br
\fC#include <podofo/podofo\&.h>\fP
.br
\fC#include <podofo/podofo\-base\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProcessor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
