.TH "src/processor.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/processor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'processor\&.h'\fP
.br
\fC#include 'ui_formconfig\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'const\&.h'\fP
.br
\fC#include 'chord\&.h'\fP
.br
\fC#include 'chordutil\&.h'\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QtMath>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QSqlQuery>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
