.TH "src/settings.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settings.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSettings>\fP
.br
\fC#include <QVariant>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettings\fP"
.br
.RI "The \fBSettings\fP class derivate the QSettings class by forcing INI format when constructor is called whith a file name\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
