.TH "SpinBoxUnit" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpinBoxUnit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spinboxunit\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBunit\fP { \fBmm\fP, \fBcm\fP, \fBin\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetValue\fP (double val, \fBunit\fP u)"
.br
.ti -1c
.RI "void \fBsetValue\fP (double val)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP (double)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinBoxUnit\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "double \fBgetValue\fP ()"
.br
.ti -1c
.RI "double \fBgetValueInUnit\fP ()"
.br
.ti -1c
.RI "QString \fBgetUnit\fP ()"
.br
.ti -1c
.RI "\fBunit\fP \fBstring2unit\fP (QString i)"
.br
.ti -1c
.RI "void \fBsetValue\fP (QString valunit)"
.br
.ti -1c
.RI "QString \fBvalue\fP ()"
.br
.ti -1c
.RI "\fBunit\fP \fBint2unit\fP (int i)"
.br
.ti -1c
.RI "double \fBgetPdfU\fP ()"
.br
.ti -1c
.RI "QString \fBvalueunit\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSpinBoxUnit::unit\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fImm \fP\fP
.TP
\fB\fIcm \fP\fP
.TP
\fB\fIin \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpinBoxUnit::SpinBoxUnit (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double SpinBoxUnit::getPdfU ()"

.SS "QString SpinBoxUnit::getUnit ()"

.SS "double SpinBoxUnit::getValue ()"

.SS "double SpinBoxUnit::getValueInUnit ()"

.SS "\fBSpinBoxUnit::unit\fP SpinBoxUnit::int2unit (int i)"

.SS "void SpinBoxUnit::setValue (QString valunit)"

.SS "void SpinBoxUnit::setValue (double val, \fBSpinBoxUnit::unit\fP u)\fC [slot]\fP"

.SS "void SpinBoxUnit::setValue (double val)\fC [slot]\fP"

.SS "\fBSpinBoxUnit::unit\fP SpinBoxUnit::string2unit (QString i)"

.SS "QString SpinBoxUnit::value ()"

.SS "void SpinBoxUnit::valueChanged (double)\fC [signal]\fP"

.SS "QString SpinBoxUnit::valueunit ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
