.TH "src/spinboxunit.cpp" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/spinboxunit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'spinboxunit\&.h'\fP
.br
\fC#include <QDebug>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
