.TH "src/spinboxunit.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/spinboxunit.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QDoubleSpinBox>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QSpacerItem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpinBoxUnit\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
