.TH "TextEdit" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextEdit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textedit\&.h>\fP
.PP
Inherits QTextEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEdit\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBinsertPlainText\fP (const QString &text, bool carriagereturn=true)"
.br
.ti -1c
.RI "void \fBsetChordLanguage\fP (QString language, QString minor)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBwheelEvent\fP (QWheelEvent *e)"
.br
.ti -1c
.RI "void \fBmouseDoubleClickEvent\fP (QMouseEvent *e)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TextEdit::TextEdit (QWidget * parent)"

.SH "Member Function Documentation"
.PP 
.SS "void TextEdit::insertPlainText (const QString & text, bool carriagereturn = \fCtrue\fP)"

.SS "void TextEdit::mouseDoubleClickEvent (QMouseEvent * e)\fC [protected]\fP"

.SS "void TextEdit::setChordLanguage (QString language, QString minor)"

.SS "void TextEdit::wheelEvent (QWheelEvent * e)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
