.TH "src/version.h" 3 "Sun Apr 15 2018" "Version 0.1" "Chord V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/version.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVERSIONWORK\fP   'v0\&.1'"
.br
.ti -1c
.RI "#define \fBDATEBUILD\fP   '2018/04/15'"
.br
.ti -1c
.RI "#define \fBGIT\fP   '62690a8f0772d7074c2933c11fdec1519c82542b'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATEBUILD   '2018/04/15'"

.SS "#define GIT   '62690a8f0772d7074c2933c11fdec1519c82542b'"

.SS "#define VERSIONWORK   'v0\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Chord V from the source code\&.
